package com.vaspshow.backend.service;

import com.vaspshow.backend.config.IntakeProperties;
import com.vaspshow.backend.dto.AuthUserResponse;
import com.vaspshow.backend.dto.DatasetSubmissionRequest;
import com.vaspshow.backend.dto.DatasetSubmissionResponse;
import com.vaspshow.backend.dto.IngestRequest;
import com.vaspshow.backend.dto.IngestSuggestionResponse;
import com.vaspshow.backend.dto.PublicDatasetSourceResponse;
import com.vaspshow.backend.dto.SubmissionReviewRequest;
import com.vaspshow.backend.exception.ApiException;
import com.vaspshow.backend.support.OutboundUrlGuard;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.jhdf.HdfFile;
import io.jhdf.api.Dataset;
import io.jhdf.api.Group;
import io.jhdf.api.Node;
import jakarta.annotation.PostConstruct;
import java.io.InputStream;
import java.lang.reflect.Array;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import org.apache.commons.compress.archivers.ArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream;
import org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream;
import org.apache.commons.compress.compressors.xz.XZCompressorInputStream;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

@Service
public class DatasetIntakeService {

  private final IntakeProperties properties;
  private final AuthService authService;
  private final ObjectMapper objectMapper;
  private final DisplayDatasetService displayDatasetService;
  private final HttpClient httpClient = HttpClient.newBuilder()
      .connectTimeout(Duration.ofSeconds(8))
      .followRedirects(HttpClient.Redirect.NORMAL)
      .build();
  private volatile String jdbcUrl;

  public DatasetIntakeService(
      IntakeProperties properties,
      AuthService authService,
      ObjectMapper objectMapper,
      DisplayDatasetService displayDatasetService
  ) {
    this.properties = properties;
    this.authService = authService;
    this.objectMapper = objectMapper;
    this.displayDatasetService = displayDatasetService;
  }

  @PostConstruct
  public void initialize() {
    try (Connection connection = openConnection();
         Statement statement = connection.createStatement()) {
      statement.execute("""
          CREATE TABLE IF NOT EXISTS DATASET_SUBMISSIONS (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            DATASET_NAME VARCHAR(180) NOT NULL,
            DATA_TYPE VARCHAR(80) NOT NULL,
            DESCRIPTION VARCHAR(2000) NOT NULL,
            PAPER_URL VARCHAR(500) NOT NULL,
            DATA_URL VARCHAR(500) NOT NULL,
            DATA_FORMAT VARCHAR(80) NOT NULL,
            LICENSE_TEXT VARCHAR(180) NOT NULL,
            PROVIDED_FIELDS VARCHAR(1000) NOT NULL,
            SUBMITTED_BY VARCHAR(64) NOT NULL,
            SUBMITTED_AT VARCHAR(40) NOT NULL,
            STATUS VARCHAR(32) NOT NULL,
            REVIEW_NOTE VARCHAR(1000) NOT NULL,
            REVIEWED_AT VARCHAR(40) NOT NULL,
            PIPELINE_STAGE VARCHAR(48) NOT NULL,
            PIPELINE_MESSAGE VARCHAR(1000) NOT NULL,
            UPDATED_AT VARCHAR(40) NOT NULL,
            PARSE_PROFILE VARCHAR(8000) DEFAULT '' NOT NULL
          )
          """);
      statement.execute("ALTER TABLE DATASET_SUBMISSIONS ADD COLUMN IF NOT EXISTS PARSE_PROFILE VARCHAR(8000) DEFAULT '' NOT NULL");
      statement.execute("CREATE INDEX IF NOT EXISTS idx_submission_user ON DATASET_SUBMISSIONS(SUBMITTED_BY, UPDATED_AT)");
      statement.execute("CREATE INDEX IF NOT EXISTS idx_submission_status ON DATASET_SUBMISSIONS(STATUS, UPDATED_AT)");
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public List<PublicDatasetSourceResponse> listPublicSources() {
    return List.of(
        new PublicDatasetSourceResponse(
            "jarvis",
            "JARVIS-DFT",
            "NIST",
            "公开 API / 下载包",
            "https://jarvis.nist.gov/",
            "晶体与二维材料的 DFT 属性",
            "人工维护候选源；已有数据接入代码可复用"
        ),
        new PublicDatasetSourceResponse(
            "materials-project",
            "Materials Project",
            "Materials Project",
            "API Key",
            "https://materialsproject.org/",
            "无机晶体结构与计算属性",
            "人工维护候选源；需配置 API 与字段映射"
        ),
        new PublicDatasetSourceResponse(
            "nomad",
            "NOMAD Repository",
            "FAIRmat",
            "公开 API",
            "https://nomad-lab.eu/",
            "多软件计算归档及工作流",
            "人工维护候选源；需配置解析与去重规则"
        ),
        new PublicDatasetSourceResponse(
            "figshare-doi",
            "DOI / Figshare 数据发布",
            "论文作者",
            "论文数据链接",
            "https://figshare.com/",
            "论文随附 HDF5、CIF、JSON 等数据",
            "人工维护候选源；由投稿审核后配置格式适配器"
        )
    );
  }

  public DatasetSubmissionResponse submit(String authorization, DatasetSubmissionRequest request) {
    AuthUserResponse user = authService.requireDatasetSubmissionAccess(authorization);
    return insertSubmission(user.username(), request);
  }

  public DatasetSubmissionResponse submitAsSystem(String submittedBy, DatasetSubmissionRequest request) {
    return insertSubmission(submittedBy == null || submittedBy.isBlank() ? "system" : submittedBy.trim(), request);
  }

  private DatasetSubmissionResponse insertSubmission(String submittedBy, DatasetSubmissionRequest request) {
    String datasetName = optional(request == null ? null : request.datasetName(), 180);
    String dataType = optional(request == null ? null : request.dataType(), 80);
    String description = required(request == null ? null : request.description(), "数据集说明", 2000);
    String paperUrl = optionalUrl(request == null ? null : request.paperUrl(), "论文链接");
    String dataUrl = optionalUrl(request == null ? null : request.dataUrl(), "数据下载或入口链接");
    if (paperUrl.isBlank() && dataUrl.isBlank()) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "请至少填写一个论文链接或数据链接");
    }
    String dataFormat = optional(request == null ? null : request.dataFormat(), 80);
    String license = optional(request == null ? null : request.license(), 180);
    String providedFields = optional(request == null ? null : request.providedFields(), 1000);
    if (datasetName.isBlank()) {
      datasetName = "待命名数据集";
    }
    if (dataType.isBlank()) {
      dataType = "待分类";
    }
    if (dataFormat.isBlank()) {
      dataFormat = "待识别";
    }
    if (license.isBlank()) {
      license = "未说明";
    }
    if (providedFields.isBlank()) {
      providedFields = "待管理员核对";
    }
    String now = Instant.now().toString();
    String sql = """
        INSERT INTO DATASET_SUBMISSIONS (
          DATASET_NAME, DATA_TYPE, DESCRIPTION, PAPER_URL, DATA_URL, DATA_FORMAT,
          LICENSE_TEXT, PROVIDED_FIELDS, SUBMITTED_BY, SUBMITTED_AT, STATUS,
          REVIEW_NOTE, REVIEWED_AT, PIPELINE_STAGE, PIPELINE_MESSAGE, UPDATED_AT
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'SUBMITTED', '', '', 'SUBMITTED',
          '已提交，等待超级管理员审核公开来源、许可证和字段可用性。', ?)
        """;
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
      statement.setString(1, datasetName);
      statement.setString(2, dataType);
      statement.setString(3, description);
      statement.setString(4, paperUrl);
      statement.setString(5, dataUrl);
      statement.setString(6, dataFormat);
      statement.setString(7, license);
      statement.setString(8, providedFields);
      statement.setString(9, submittedBy);
      statement.setString(10, now);
      statement.setString(11, now);
      statement.executeUpdate();
      try (ResultSet generated = statement.getGeneratedKeys()) {
        generated.next();
        return findById(generated.getLong(1));
      }
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public List<DatasetSubmissionResponse> listSubmissions(String authorization) {
    AuthUserResponse user = authService.requireDatasetSubmissionAccess(authorization);
    boolean reviewAccess = AuthService.ROLE_SUPER_ADMIN.equals(user.role());
    String sql = reviewAccess
        ? "SELECT * FROM DATASET_SUBMISSIONS ORDER BY UPDATED_AT DESC, ID DESC"
        : "SELECT * FROM DATASET_SUBMISSIONS WHERE SUBMITTED_BY = ? ORDER BY UPDATED_AT DESC, ID DESC";
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(sql)) {
      if (!reviewAccess) {
        statement.setString(1, user.username());
      }
      try (ResultSet rs = statement.executeQuery()) {
        List<DatasetSubmissionResponse> submissions = new ArrayList<>();
        while (rs.next()) {
          submissions.add(fromResult(rs));
        }
        return submissions;
      }
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public DatasetSubmissionResponse review(
      String authorization,
      long id,
      SubmissionReviewRequest request
  ) {
    authService.requireDatasetReviewAccess(authorization);
    String decision = normalizeDecision(request == null ? null : request.decision());
    String note = optional(request == null ? null : request.note(), 1000);
    String now = Instant.now().toString();
    String stage = "APPROVED".equals(decision) ? "SOURCE_APPROVED" : "CLOSED";
    String message = "APPROVED".equals(decision)
        ? "公开来源已批准，等待进入格式适配和入库校验阶段。"
        : "该投稿未进入数据接入管线。";
    String sql = """
        UPDATE DATASET_SUBMISSIONS
        SET STATUS = ?, REVIEW_NOTE = ?, REVIEWED_AT = ?, PIPELINE_STAGE = ?, PIPELINE_MESSAGE = ?, UPDATED_AT = ?
        WHERE ID = ?
        """;
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(sql)) {
      statement.setString(1, decision);
      statement.setString(2, note);
      statement.setString(3, now);
      statement.setString(4, stage);
      statement.setString(5, message);
      statement.setString(6, now);
      statement.setLong(7, id);
      if (statement.executeUpdate() == 0) {
        throw new ApiException(HttpStatus.NOT_FOUND, "找不到数据集投稿: " + id);
      }
      return findById(id);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public DatasetSubmissionResponse preparePipeline(String authorization, long id) {
    authService.requireDatasetReviewAccess(authorization);
    DatasetSubmissionResponse submission = findById(id);
    if (!"APPROVED".equals(submission.status())) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "仅已批准的数据集可以进入接入管线");
    }
    String message = "来源登记完成；需为 " + submission.dataFormat()
        + " 配置受控解析适配器、字段映射和记录数校验后发布到展示库。";
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DATASET_SUBMISSIONS
             SET PIPELINE_STAGE = 'ADAPTER_REQUIRED', PIPELINE_MESSAGE = ?, UPDATED_AT = ?
             WHERE ID = ?
             """)) {
      statement.setString(1, message);
      statement.setString(2, now);
      statement.setLong(3, id);
      statement.executeUpdate();
      return findById(id);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public DatasetSubmissionResponse profileSubmission(String authorization, long id) {
    authService.requireDatasetReviewAccess(authorization);
    return runProfile(id, true);
  }

  public DatasetSubmissionResponse profileSubmissionAsSystem(long id) {
    return runProfile(id, false);
  }

  private DatasetSubmissionResponse runProfile(long id, boolean strict) {
    DatasetSubmissionResponse submission = findById(id);
    if (!"APPROVED".equals(submission.status())) {
      if (strict) {
        throw new ApiException(HttpStatus.BAD_REQUEST, "仅已批准来源可进行自动解析预检");
      }
      return submission;
    }
    Map<String, Object> profile = new LinkedHashMap<>();
    profile.put("parsedAt", Instant.now().toString());
    String stage;
    String message;
    try {
      DownloadSample sample = downloadSample(submission.dataUrl());
      profile.put("fileName", sample.fileName());
      profile.put("sizeBytes", sample.totalSize());
      profile.put("sampleBytes", sample.bytes().length);
      profile.put("sampled", sample.truncated());
      String format = detectSampleFormat(sample);
      profile.put("format", format);
      parseSample(profile, format, sample);
      stage = "VALIDATED";
      Object summary = profile.getOrDefault("summary", "已提取字段与结构样本");
      message = "自动解析预检完成：格式 " + format + "；" + summary
          + "。仍需人工确认字段映射/单位后才能入库发布。";
    } catch (Exception ex) {
      profile.put("status", "failed");
      profile.put("warning", ex.getMessage() == null ? ex.getClass().getSimpleName() : ex.getMessage());
      stage = "ADAPTER_REQUIRED";
      message = "自动解析预检未完成：" + profile.get("warning") + "。可人工下载样本后再配置适配器。";
    }
    return applyProfile(id, stage, message, toJson(profile));
  }

  private DatasetSubmissionResponse applyProfile(long id, String stage, String message, String profileJson) {
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DATASET_SUBMISSIONS
             SET PIPELINE_STAGE = ?, PIPELINE_MESSAGE = ?, PARSE_PROFILE = ?, UPDATED_AT = ?
             WHERE ID = ?
             """)) {
      statement.setString(1, stage);
      statement.setString(2, limitText(message, 1000));
      statement.setString(3, limitText(profileJson, 8000));
      statement.setString(4, now);
      statement.setLong(5, id);
      statement.executeUpdate();
      return findById(id);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  private DownloadSample downloadSample(String dataUrl) throws Exception {
    String url = dataUrl == null ? "" : dataUrl.trim();
    if (!url.startsWith("http://") && !url.startsWith("https://")) {
      throw new IllegalStateException("数据链接不是可下载的 http/https 地址");
    }
    if (!OutboundUrlGuard.isSafe(url)) {
      // SSRF guard: refuse to download from a host that resolves to an internal address.
      throw new IllegalStateException("下载链接未通过安全校验（禁止内网/环回/链路本地等地址）");
    }
    int capMb = Math.max(1, properties.getDiscovery().getAutoAdapt().getMaxDownloadMb());
    int sampleMb = Math.max(1, properties.getDiscovery().getAutoAdapt().getSampleMb());
    long capBytes = capMb * 1024L * 1024L;
    long sampleBytes = sampleMb * 1024L * 1024L;
    String contentType = "";
    long declaredTotal = -1L;
    try {
      HttpRequest head = HttpRequest.newBuilder(URI.create(url))
          .method("HEAD", HttpRequest.BodyPublishers.noBody())
          .timeout(Duration.ofSeconds(10))
          .header("User-Agent", "VASP-Show-auto-adapter")
          .build();
      HttpResponse<Void> headResponse = httpClient.send(head, HttpResponse.BodyHandlers.discarding());
      contentType = headResponse.headers().firstValue("content-type").orElse("");
      declaredTotal = headResponse.headers().firstValueAsLong("content-length").orElse(-1L);
    } catch (Exception ignored) {
      // HEAD unsupported; we cap (or range-sample) the GET instead.
    }
    // Large files are head-sampled via an HTTP Range request so we can profile
    // datasets far bigger than the full-download cap without fetching everything.
    boolean rangeSample = declaredTotal > capBytes;
    long effectiveCap = rangeSample ? sampleBytes : capBytes;
    HttpRequest.Builder getBuilder = HttpRequest.newBuilder(URI.create(url))
        .GET()
        .timeout(Duration.ofSeconds(40))
        .header("User-Agent", "VASP-Show-auto-adapter");
    if (rangeSample) {
      getBuilder.header("Range", "bytes=0-" + (effectiveCap - 1));
    }
    HttpResponse<InputStream> response = httpClient.send(getBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IllegalStateException("下载失败，HTTP " + response.statusCode());
    }
    if (contentType.isBlank()) {
      contentType = response.headers().firstValue("content-type").orElse("");
    }
    boolean truncated = rangeSample;
    byte[] bytes;
    try (InputStream in = response.body();
         java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream()) {
      byte[] chunk = new byte[64 * 1024];
      long total = 0;
      int read;
      while ((read = in.read(chunk)) != -1) {
        if (total + read > effectiveCap) {
          buffer.write(chunk, 0, (int) (effectiveCap - total));
          truncated = true;
          break;
        }
        buffer.write(chunk, 0, read);
        total += read;
      }
      bytes = buffer.toByteArray();
    }
    if (bytes.length == 0) {
      throw new IllegalStateException("下载内容为空");
    }
    long total = declaredTotal > 0 ? declaredTotal : bytes.length;
    return new DownloadSample(bytes, total, truncated, fileNameFromUrl(url), contentType);
  }

  private static String detectSampleFormat(DownloadSample sample) {
    byte[] b = sample.bytes();
    if (b.length >= 4 && (b[0] & 0xFF) == 0x89 && b[1] == 'H' && b[2] == 'D' && b[3] == 'F') {
      return "HDF5";
    }
    if (b.length >= 4 && b[0] == 'P' && b[1] == 'K' && b[2] == 3 && b[3] == 4) {
      return "ZIP";
    }
    if (b.length >= 2 && (b[0] & 0xFF) == 0x1f && (b[1] & 0xFF) == 0x8b) {
      return "GZIP";
    }
    if (b.length >= 6 && (b[0] & 0xFF) == 0xFD && b[1] == '7' && b[2] == 'z'
        && b[3] == 'X' && b[4] == 'Z' && b[5] == 0x00) {
      return "XZ";
    }
    if (b.length >= 3 && b[0] == 'B' && b[1] == 'Z' && b[2] == 'h') {
      return "BZIP2";
    }
    if (b.length >= 4 && (b[0] & 0xFF) == 0x28 && (b[1] & 0xFF) == 0xB5
        && (b[2] & 0xFF) == 0x2F && (b[3] & 0xFF) == 0xFD) {
      return "ZSTD";
    }
    if (b.length >= 265 && b[257] == 'u' && b[258] == 's' && b[259] == 't'
        && b[260] == 'a' && b[261] == 'r') {
      return "TAR";
    }
    String name = sample.fileName().toLowerCase(Locale.ROOT);
    String ct = sample.contentType().toLowerCase(Locale.ROOT);
    if (name.endsWith(".h5") || name.endsWith(".hdf5")) return "HDF5";
    if (name.endsWith(".zip")) return "ZIP";
    if (name.endsWith(".tar.gz") || name.endsWith(".tgz") || name.endsWith(".gz")) return "GZIP";
    if (name.endsWith(".tar.xz") || name.endsWith(".txz") || name.endsWith(".xz")) return "XZ";
    if (name.endsWith(".tar.bz2") || name.endsWith(".tbz2") || name.endsWith(".bz2")) return "BZIP2";
    if (name.endsWith(".tar.zst") || name.endsWith(".tzst") || name.endsWith(".zst")) return "ZSTD";
    if (name.endsWith(".tar")) return "TAR";
    if (name.endsWith(".cif")) return "CIF";
    if (name.contains("poscar") || name.contains("contcar")) return "POSCAR";
    if (name.endsWith(".extxyz")) return "EXTXYZ";
    if (name.endsWith(".xyz")) return "XYZ";
    if (name.endsWith(".jsonl") || name.endsWith(".ndjson")) return "JSONL";
    if (name.endsWith(".json") || ct.contains("application/json")) return "JSON";
    if (name.endsWith(".tsv")) return "TSV";
    if (!looksLikeText(b)) return "BINARY";
    if (name.endsWith(".csv") || ct.contains("text/csv")) return "CSV";
    String headText = new String(b, 0, Math.min(b.length, 512), StandardCharsets.UTF_8).trim();
    String[] headLines = headText.split("\\r?\\n");
    if (headLines.length > 0) {
      String first = headLines[0].trim();
      if (first.matches("\\d+")) return "XYZ";
      if (headLines.length > 1 && first.contains("\t")) return "TSV";
      if (headLines.length > 1 && (first.contains(",") || first.contains(";"))) return "CSV";
      if (headLines.length > 1 && first.startsWith("{") && headLines[1].trim().startsWith("{")) return "JSONL";
    }
    if (headText.startsWith("{") || headText.startsWith("[")) return "JSON";
    return "UNKNOWN";
  }

  private static boolean looksLikeText(byte[] bytes) {
    int limit = Math.min(bytes.length, 2048);
    if (limit == 0) {
      return false;
    }
    int suspicious = 0;
    for (int i = 0; i < limit; i += 1) {
      int value = bytes[i] & 0xFF;
      if (value == 0) {
        return false;
      }
      if (value < 0x09 || (value > 0x0D && value < 0x20)) {
        suspicious += 1;
      }
    }
    return suspicious <= Math.max(4, limit / 100);
  }

  private static boolean isPlausibleCsvHeader(String header) {
    if (header == null || header.isBlank() || header.length() > 4000) {
      return false;
    }
    boolean hasDelimiter = header.contains(",") || header.contains("\t") || header.contains(";");
    if (!hasDelimiter) {
      return false;
    }
    for (int i = 0; i < header.length(); i += 1) {
      char ch = header.charAt(i);
      if (ch == '\uFFFD' || (Character.isISOControl(ch) && ch != '\t')) {
        return false;
      }
    }
    return true;
  }

  private void parseSample(Map<String, Object> profile, String format, DownloadSample sample) {
    try {
      switch (format) {
        case "JSON" -> parseJson(profile, sample);
        case "JSONL" -> parseJsonl(profile, sample);
        case "CSV", "TSV" -> parseDelimited(profile, format, sample);
        case "XYZ", "EXTXYZ" -> parseXyz(profile, sample);
        case "CIF" -> parseCif(profile, sample);
        case "POSCAR" -> parsePoscar(profile, sample);
        case "HDF5" -> parseHdf5(profile, sample);
        case "ZIP" -> parseZip(profile, sample);
        case "TAR" -> parseTar(profile, sample, "TAR");
        case "GZIP", "XZ", "BZIP2", "ZSTD", "BINARY" -> parseCompressedOrBinary(profile, format, sample);
        default -> {
          profile.put("status", "unsupported");
          profile.put("summary", "暂不支持自动解析该格式，需人工配置适配器。");
          profile.put("detectedFields", "metadata only");
        }
      }
    } catch (Exception ex) {
      profile.put("status", "partial");
      profile.put("warning", "解析样本出错: " + (ex.getMessage() == null ? ex.getClass().getSimpleName() : ex.getMessage()));
    }
  }

  private void parseJson(Map<String, Object> profile, DownloadSample sample) throws Exception {
    JsonNode root = objectMapper.readTree(sample.bytes());
    List<String> fields = new ArrayList<>();
    long records;
    if (root.isArray()) {
      records = root.size();
      if (!root.isEmpty() && root.get(0).isObject()) {
        root.get(0).fieldNames().forEachRemaining(fields::add);
      }
    } else if (root.isObject()) {
      root.fieldNames().forEachRemaining(fields::add);
      JsonNode dataNode = root.has("data") ? root.get("data") : (root.has("records") ? root.get("records") : null);
      records = (dataNode != null && dataNode.isArray()) ? dataNode.size() : 1;
      if (dataNode != null && dataNode.isArray() && !dataNode.isEmpty() && dataNode.get(0).isObject()) {
        List<String> inner = new ArrayList<>();
        dataNode.get(0).fieldNames().forEachRemaining(inner::add);
        profile.put("recordFields", capList(inner, 40));
      }
    } else {
      records = 1;
    }
    profile.put("status", "parsed");
    profile.put("fields", capList(fields, 40));
    profile.put("recordEstimate", sample.truncated() ? "≥ " + records + "（样本截断）" : String.valueOf(records));
    profile.put("summary", "JSON 字段 " + fields.size() + " 个，记录约 " + records);
    profile.put("detectedFields", mapToScientificFields(String.join(" ", fields)));
  }

  private void parseJsonl(Map<String, Object> profile, DownloadSample sample) throws Exception {
    String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
    List<String> fields = new ArrayList<>();
    long records = 0;
    for (String line : lines) {
      if (line.isBlank()) {
        continue;
      }
      records += 1;
      if (fields.isEmpty()) {
        JsonNode node = objectMapper.readTree(line);
        if (node.isObject()) {
          node.fieldNames().forEachRemaining(fields::add);
        }
      }
    }
    profile.put("status", "parsed");
    profile.put("fields", capList(fields, 40));
    profile.put("recordEstimate", sample.truncated() ? "≥ " + records + "（样本截断）" : String.valueOf(records));
    profile.put("summary", "JSONL/NDJSON 字段 " + fields.size() + " 个，记录约 " + records);
    profile.put("detectedFields", mapToScientificFields(String.join(" ", fields)));
  }

  private void parseDelimited(Map<String, Object> profile, String format, DownloadSample sample) {
    String text = new String(sample.bytes(), StandardCharsets.UTF_8);
    String[] lines = text.split("\\r?\\n");
    int dataLines = 0;
    for (String line : lines) {
      if (!line.isBlank()) dataLines++;
    }
    String header = lines.length > 0 ? lines[0] : "";
    if (!isPlausibleCsvHeader(header)) {
      profile.put("status", "unsupported");
      profile.put("fields", List.of());
      profile.put("summary", "样本不像有效 " + format + " 文本，可能是压缩包或二进制文件；已停止按表格解析，避免乱码字段。");
      profile.put("detectedFields", "metadata only");
      return;
    }
    String delimiter = "TSV".equals(format) ? "\t" : (header.contains("\t") ? "\t" : (header.contains(";") ? ";" : ","));
    List<String> columns = new ArrayList<>();
    for (String col : header.split(java.util.regex.Pattern.quote(delimiter))) {
      String c = col.trim().replaceAll("^\"|\"$", "");
      if (!c.isBlank()) columns.add(c);
    }
    long rows = Math.max(0, dataLines - 1);
    profile.put("status", "parsed");
    profile.put("fields", capList(columns, 40));
    profile.put("recordEstimate", sample.truncated() ? "≥ " + rows + "（样本截断）" : String.valueOf(rows));
    profile.put("summary", format + " 列 " + columns.size() + " 个，数据行约 " + rows);
    profile.put("detectedFields", mapToScientificFields(String.join(" ", columns)));
  }

  private void parseCompressedOrBinary(Map<String, Object> profile, String format, DownloadSample sample) {
    profile.put("status", "unsupported");
    profile.put("fields", List.of());
    profile.put("detectedFields", "metadata only");
    if ("BINARY".equals(format)) {
      profile.put("summary", "检测到二进制样本，当前不会按 CSV/文本解析。请确认原始格式，或先解包后按内部文件接入。");
      return;
    }
    if ("ZSTD".equals(format)) {
      profile.put("summary", "ZSTD 压缩文件已识别；当前运行环境只做外层识别，需安装 Zstandard 解压适配器后解析内部文件。");
      return;
    }
    try {
      InnerBytes decompressed = decompressSample(format, sample);
      String innerName = stripCompressionExtension(sample.fileName());
      DownloadSample inner = new DownloadSample(
          decompressed.bytes(),
          decompressed.bytes().length,
          sample.truncated() || decompressed.truncated(),
          innerName,
          "");
      String innerFormat = detectSampleFormat(inner);
      profile.put("containerFormat", format);
      profile.put("innerFile", innerName);
      profile.put("innerFormat", innerFormat);
      profile.put("innerSampleBytes", inner.bytes().length);
      if ("TAR".equals(innerFormat) || innerName.toLowerCase(Locale.ROOT).endsWith(".tar")) {
        parseTar(profile, inner, format);
      } else {
        parseSample(profile, innerFormat, inner);
        Object innerSummary = profile.getOrDefault("summary", "已完成内部样本解析");
        profile.put("summary", format + " 解压后识别为 " + innerFormat + "；" + innerSummary);
      }
    } catch (Exception ex) {
      profile.put("summary", format + " 压缩文件已识别，但样本解压失败："
          + (ex.getMessage() == null ? ex.getClass().getSimpleName() : ex.getMessage())
          + "。若远程文件很大，当前 Range 样本可能不足以完整解压。");
    }
  }

  private void parseXyz(Map<String, Object> profile, DownloadSample sample) {
    String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
    int natoms = 0;
    try {
      natoms = Integer.parseInt(lines[0].trim());
    } catch (Exception ignored) {
      // First line is not an atom count; leave at 0.
    }
    Set<String> elements = new LinkedHashSet<>();
    int limit = Math.min(lines.length, 2 + Math.max(natoms, 0));
    for (int i = 2; i < limit; i++) {
      String[] parts = lines[i].trim().split("\\s+");
      if (parts.length >= 4 && parts[0].matches("[A-Za-z]{1,2}")) {
        elements.add(parts[0]);
      }
    }
    profile.put("status", "parsed");
    profile.put("atomsInFirstFrame", natoms);
    profile.put("elements", new ArrayList<>(elements));
    profile.put("summary", "XYZ 首帧 " + natoms + " 原子，元素 " + String.join("/", elements));
    profile.put("detectedFields", "structure/coordinates");
  }

  private void parseCif(Map<String, Object> profile, DownloadSample sample) {
    String text = new String(sample.bytes(), StandardCharsets.UTF_8);
    String formula = "";
    for (String raw : text.split("\\r?\\n")) {
      String line = raw.trim();
      if (line.startsWith("_chemical_formula_sum")) {
        formula = line.substring("_chemical_formula_sum".length()).trim().replaceAll("['\"]", "");
      }
    }
    Set<String> elements = new LinkedHashSet<>();
    java.util.regex.Matcher m = java.util.regex.Pattern.compile("([A-Z][a-z]?)").matcher(formula);
    while (m.find()) {
      elements.add(m.group(1));
    }
    profile.put("status", "parsed");
    profile.put("formula", formula);
    profile.put("elements", new ArrayList<>(elements));
    profile.put("summary", "CIF 晶体结构，化学式 " + (formula.isBlank() ? "未标注" : formula));
    profile.put("detectedFields", "structure/coordinates, lattice");
  }

  private void parsePoscar(Map<String, Object> profile, DownloadSample sample) {
    String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
    List<String> species = new ArrayList<>();
    if (lines.length > 5) {
      for (String s : lines[5].trim().split("\\s+")) {
        if (s.matches("[A-Z][a-z]?")) species.add(s);
      }
    }
    profile.put("status", "parsed");
    profile.put("elements", species);
    profile.put("summary", "POSCAR/CONTCAR 结构，元素 " + String.join("/", species));
    profile.put("detectedFields", "structure/coordinates, lattice");
  }

  private void parseHdf5(Map<String, Object> profile, DownloadSample sample) throws Exception {
    if (sample.truncated()) {
      profile.put("status", "too_large");
      profile.put("summary", "HDF5 超过下载上限，仅取到部分字节，无法完整解析；建议人工下载完整文件");
      profile.put("detectedFields", "metadata only");
      return;
    }
    Path temp = Files.createTempFile("vasp-adapter-", ".h5");
    try {
      Files.write(temp, sample.bytes());
      try (HdfFile hdf = new HdfFile(temp)) {
        List<String> datasets = new ArrayList<>();
        int[] groupCount = {0};
        collectHdf(hdf, datasets, groupCount, 0);
        profile.put("status", "parsed");
        profile.put("fields", capList(datasets, 40));
        profile.put("topLevelGroups", groupCount[0]);
        profile.put("summary", "HDF5 顶层组 " + groupCount[0] + " 个，dataset " + datasets.size() + " 个");
        profile.put("detectedFields", mapToScientificFields(String.join(" ", datasets)));
      }
    } finally {
      Files.deleteIfExists(temp);
    }
  }

  private void collectHdf(Group group, List<String> datasets, int[] groupCount, int depth) {
    if (depth > 3 || datasets.size() >= 60) {
      return;
    }
    for (Node node : group.getChildren().values()) {
      if (node instanceof Group childGroup) {
        if (depth == 0) {
          groupCount[0]++;
        }
        collectHdf(childGroup, datasets, groupCount, depth + 1);
      } else if (node instanceof Dataset dataset) {
        if (datasets.size() < 60) {
          datasets.add(node.getName() + java.util.Arrays.toString(dataset.getDimensions()));
        }
      }
    }
  }

  private void parseZip(Map<String, Object> profile, DownloadSample sample) throws Exception {
    List<String> entries = listZipEntries(sample.bytes());
    profile.put("archiveEntries", capList(entries, 40));
    profile.put("entryCount", entries.size());
    String selected = bestArchiveEntry(entries);
    if (selected != null) {
      InnerBytes selectedBytes = readZipEntry(sample.bytes(), selected);
      parseArchiveEntry(profile, "ZIP", sample, selected, selectedBytes);
      return;
    }
    profile.put("status", entries.isEmpty() ? "partial" : "parsed");
    profile.put("fields", capList(entries, 40));
    profile.put("summary", "ZIP 内文件 " + entries.size() + " 个；未找到可直接预检的 CIF/XYZ/HDF5/JSON/JSONL/CSV/TSV 等文件。");
    profile.put("detectedFields", mapToScientificFields(String.join(" ", entries)));
  }

  private void parseTar(Map<String, Object> profile, DownloadSample sample, String containerFormat) throws Exception {
    List<String> entries = listTarEntries(sample.bytes());
    profile.put("containerFormat", containerFormat);
    profile.put("archiveEntries", capList(entries, 40));
    profile.put("entryCount", entries.size());
    String selected = bestArchiveEntry(entries);
    if (selected != null) {
      InnerBytes selectedBytes = readTarEntry(sample.bytes(), selected);
      parseArchiveEntry(profile, containerFormat.equals("TAR") ? "TAR" : containerFormat + " -> TAR", sample, selected, selectedBytes);
      return;
    }
    profile.put("status", entries.isEmpty() ? "partial" : "parsed");
    profile.put("fields", capList(entries, 40));
    profile.put("summary", containerFormat + " 归档内文件 " + entries.size() + " 个；未找到可直接预检的结构或表格文件。");
    profile.put("detectedFields", mapToScientificFields(String.join(" ", entries)));
  }

  private List<String> listZipEntries(byte[] bytes) throws Exception {
    List<String> entries = new ArrayList<>();
    try (ZipInputStream zip = new ZipInputStream(new java.io.ByteArrayInputStream(bytes))) {
      ZipEntry entry;
      while ((entry = zip.getNextEntry()) != null && entries.size() < 60) {
        if (!entry.isDirectory()) {
          entries.add(entry.getName());
        }
      }
    }
    return entries;
  }

  private List<String> listTarEntries(byte[] bytes) throws Exception {
    List<String> entries = new ArrayList<>();
    try (TarArchiveInputStream tar = new TarArchiveInputStream(new java.io.ByteArrayInputStream(bytes))) {
      ArchiveEntry entry;
      while ((entry = tar.getNextEntry()) != null && entries.size() < 60) {
        if (!entry.isDirectory()) {
          entries.add(entry.getName());
        }
      }
    }
    return entries;
  }

  private InnerBytes readZipEntry(byte[] bytes, String entryName) throws Exception {
    try (ZipInputStream zip = new ZipInputStream(new java.io.ByteArrayInputStream(bytes))) {
      ZipEntry entry;
      while ((entry = zip.getNextEntry()) != null) {
        if (!entry.isDirectory() && entryName.equals(entry.getName())) {
          return readLimited(zip, archiveInnerByteLimit());
        }
      }
    }
    return new InnerBytes(new byte[0], false);
  }

  private InnerBytes readTarEntry(byte[] bytes, String entryName) throws Exception {
    try (TarArchiveInputStream tar = new TarArchiveInputStream(new java.io.ByteArrayInputStream(bytes))) {
      ArchiveEntry entry;
      while ((entry = tar.getNextEntry()) != null) {
        if (!entry.isDirectory() && entryName.equals(entry.getName())) {
          return readLimited(tar, archiveInnerByteLimit());
        }
      }
    }
    return new InnerBytes(new byte[0], false);
  }

  private void parseArchiveEntry(
      Map<String, Object> profile,
      String containerFormat,
      DownloadSample outerSample,
      String entryName,
      InnerBytes selectedBytes
  ) {
    if (selectedBytes.bytes().length == 0) {
      profile.put("status", "partial");
      profile.put("summary", containerFormat + " 内部文件 " + entryName + " 为空或无法读取。");
      profile.put("detectedFields", "metadata only");
      return;
    }
    DownloadSample inner = new DownloadSample(
        selectedBytes.bytes(),
        selectedBytes.bytes().length,
        outerSample.truncated() || selectedBytes.truncated(),
        entryName,
        "");
    String innerFormat = detectSampleFormat(inner);
    profile.put("containerFormat", containerFormat);
    profile.put("selectedEntry", entryName);
    profile.put("innerFormat", innerFormat);
    profile.put("innerSampleBytes", inner.bytes().length);
    profile.put("innerSampleTruncated", inner.truncated());
    parseSample(profile, innerFormat, inner);
    Object innerSummary = profile.getOrDefault("summary", "已完成内部样本解析");
    profile.put("summary", containerFormat + " 内部文件 " + entryName + " 识别为 " + innerFormat + "；" + innerSummary);
  }

  private InnerBytes decompressSample(String format, DownloadSample sample) throws Exception {
    java.io.InputStream raw = new java.io.ByteArrayInputStream(sample.bytes());
    java.io.InputStream in = switch (format) {
      case "GZIP" -> new GzipCompressorInputStream(raw);
      case "XZ" -> new XZCompressorInputStream(raw);
      case "BZIP2" -> new BZip2CompressorInputStream(raw);
      default -> raw;
    };
    try (java.io.InputStream autoClose = in) {
      return readLimited(autoClose, archiveInnerByteLimit());
    }
  }

  private int archiveInnerByteLimit() {
    return Math.max(1, properties.getDiscovery().getAutoAdapt().getSampleMb()) * 1024 * 1024;
  }

  private static InnerBytes readLimited(java.io.InputStream in, int maxBytes) throws Exception {
    try (java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream()) {
      byte[] chunk = new byte[64 * 1024];
      int total = 0;
      int read;
      boolean truncated = false;
      while ((read = in.read(chunk)) != -1) {
        if (total + read > maxBytes) {
          buffer.write(chunk, 0, maxBytes - total);
          truncated = true;
          break;
        }
        buffer.write(chunk, 0, read);
        total += read;
      }
      return new InnerBytes(buffer.toByteArray(), truncated);
    }
  }

  private static String bestArchiveEntry(List<String> entries) {
    String best = null;
    int bestScore = 0;
    for (String entry : entries) {
      int score = archiveEntryScore(entry);
      if (score > bestScore) {
        best = entry;
        bestScore = score;
      }
    }
    return best;
  }

  private static int archiveEntryScore(String entry) {
    String name = entry == null ? "" : entry.toLowerCase(Locale.ROOT);
    if (name.endsWith("/") || name.contains("__macosx/")) return 0;
    if (name.endsWith(".h5") || name.endsWith(".hdf5")) return 100;
    if (name.endsWith(".cif") || name.endsWith(".extxyz") || name.endsWith(".xyz")) return 95;
    if (name.endsWith("poscar") || name.endsWith("contcar") || name.contains("/poscar") || name.contains("/contcar")) return 92;
    if (name.endsWith(".json") || name.endsWith(".jsonl") || name.endsWith(".ndjson")) return 88;
    if (name.endsWith(".csv") || name.endsWith(".tsv")) return 84;
    if (name.endsWith(".tar") || name.endsWith(".zip") || name.endsWith(".gz")
        || name.endsWith(".xz") || name.endsWith(".bz2") || name.endsWith(".tgz")
        || name.endsWith(".txz")) return 70;
    if (name.contains("readme") || name.contains("license")) return 10;
    return 0;
  }

  private static String stripCompressionExtension(String fileName) {
    String name = fileName == null || fileName.isBlank() ? "decompressed" : fileName;
    String lower = name.toLowerCase(Locale.ROOT);
    for (String suffix : List.of(".tar.gz", ".tgz", ".tar.xz", ".txz", ".tar.bz2", ".tbz2", ".gz", ".xz", ".bz2")) {
      if (lower.endsWith(suffix)) {
        return name.substring(0, name.length() - suffix.length()) + (suffix.startsWith(".tar") || suffix.equals(".tgz") || suffix.equals(".txz") || suffix.equals(".tbz2") ? ".tar" : "");
      }
    }
    return name + ".decompressed";
  }

  private static List<String> capList(List<String> values, int max) {
    return values.size() <= max ? values : new ArrayList<>(values.subList(0, max));
  }

  private static String mapToScientificFields(String text) {
    String t = text.toLowerCase(Locale.ROOT);
    Set<String> fields = new LinkedHashSet<>();
    if (t.contains("coord") || t.contains("position") || t.contains("structure")
        || t.contains("xyz") || t.contains("cell") || t.contains("lattice")) {
      fields.add("structure/coordinates");
    }
    if (t.contains("energy") || t.contains("energies")) fields.add("energy");
    if (t.contains("force")) fields.add("force");
    if (t.contains("stress") || t.contains("virial")) fields.add("stress");
    if (t.contains("gap") || t.contains("homo") || t.contains("lumo")) fields.add("bandgap/electronic");
    if (t.contains("smiles")) fields.add("smiles");
    if (fields.isEmpty()) fields.add("metadata only");
    return String.join(", ", fields);
  }

  private String toJson(Map<String, Object> profile) {
    try {
      return objectMapper.writeValueAsString(profile);
    } catch (Exception ex) {
      return "{}";
    }
  }

  private static String limitText(String value, int maxLength) {
    String text = value == null ? "" : value;
    return text.length() <= maxLength ? text : text.substring(0, maxLength);
  }

  private static String fileNameFromUrl(String url) {
    try {
      String path = URI.create(url).getPath();
      String[] segments = path.split("/");
      // Repositories like Zenodo end file URLs with .../files/<name>/content,
      // so skip generic trailing segments to recover the real filename.
      for (int i = segments.length - 1; i >= 0; i -= 1) {
        String segment = segments[i];
        if (segment.isBlank() || "content".equals(segment) || "download".equals(segment)) {
          continue;
        }
        return segment;
      }
      return "";
    } catch (Exception ex) {
      return "";
    }
  }

  private record DownloadSample(byte[] bytes, long totalSize, boolean truncated, String fileName, String contentType) {
  }

  private record InnerBytes(byte[] bytes, boolean truncated) {
  }

  @FunctionalInterface
  private interface DatasetPredicate {
    boolean test(String name, Dataset dataset);
  }

  private record Hdf5GroupCandidate(
      String path,
      Dataset coordinates,
      Dataset atomLabels,
      Dataset energies,
      Dataset forces,
      Dataset lattice
  ) {
  }

  private record Hdf5AtomLabel(String element, int atomicNumber) {
  }

  public IngestSuggestionResponse ingestSuggestion(String authorization, long id) {
    authService.requireDatasetReviewAccess(authorization);
    DatasetSubmissionResponse submission = findById(id);
    String datasetKey = "intake_" + id;
    String datasetName = submission.datasetName() == null || submission.datasetName().isBlank()
        ? "自动入库数据集 #" + id
        : submission.datasetName();
    String format = "";
    List<String> fields = new ArrayList<>();
    try {
      if (submission.parseProfile() != null && !submission.parseProfile().isBlank()) {
        JsonNode profile = objectMapper.readTree(submission.parseProfile());
        format = profile.path("format").asText("");
        JsonNode fieldsNode = profile.path("recordFields").isArray()
            ? profile.path("recordFields")
            : profile.path("fields");
        if (fieldsNode.isArray()) {
          fieldsNode.forEach(node -> fields.add(node.asText("")));
        }
      }
    } catch (Exception ignored) {
      // No usable parse profile; the suggestion is simply empty.
    }
    boolean tabular = isTabularFormat(format);
    boolean structure = isStructureFormat(format);
    boolean supported = tabular || structure;
    Map<String, String> suggested = tabular ? suggestMapping(fields) : Map.of();
    String note;
    if (structure) {
      note = "结构格式 " + format + " 可直接入库：结构适配器将解析元素/坐标/化学式（extxyz 另取 energy）并写入展示库数据集 "
          + datasetKey + "，无需字段映射；前若干条结构，仍需人工核对。";
    } else if (tabular) {
      note = "已按字段名建议映射，可编辑后确认入库；将写入展示库数据集 " + datasetKey + "（前若干条，需人工确认）。";
    } else {
      note = "当前解析格式为 " + (format.isBlank() ? "未知" : format)
          + "，支持 CSV/TSV/JSON/JSONL 表格与 XYZ/EXTXYZ/CIF/POSCAR/HDF5 结构来源直接入库；其它格式需人工适配器。";
    }
    return new IngestSuggestionResponse(datasetKey, datasetName, supported, format, fields, suggested, note);
  }

  public DatasetSubmissionResponse ingestSubmission(String authorization, long id, IngestRequest request) {
    authService.requireDatasetReviewAccess(authorization);
    DatasetSubmissionResponse submission = findById(id);
    if (!"APPROVED".equals(submission.status())) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "仅已批准来源可入库");
    }
    int limit = request != null && request.limit() != null
        ? Math.max(1, Math.min(request.limit(), 1000))
        : 200;
    String datasetKey = "intake_" + id;
    String datasetName = request != null && request.datasetName() != null && !request.datasetName().isBlank()
        ? request.datasetName().trim()
        : (submission.datasetName() == null || submission.datasetName().isBlank() ? "自动入库数据集 #" + id : submission.datasetName());

    List<Map<String, String>> rows;
    String modeNote;
    try {
      DownloadSample sample = downloadSample(submission.dataUrl());
      String format = detectSampleFormat(sample);
      if (isStructureFormat(format)) {
        rows = extractStructureRecords(format, sample, limit, datasetKey, datasetName);
        modeNote = "结构适配器（" + format + "）解析坐标/元素/化学式";
      } else if (isTabularFormat(format)) {
        Map<String, String> mapping = request == null || request.mapping() == null ? Map.of() : request.mapping();
        if (mapping.isEmpty()) {
          throw new ApiException(HttpStatus.BAD_REQUEST, "请先确认字段映射");
        }
        rows = mapTabularRecords(extractTabularRecords(format, sample, limit), mapping, datasetKey, datasetName);
        modeNote = "表格来源（" + format + "）按确认的字段映射";
      } else {
        throw new ApiException(HttpStatus.BAD_REQUEST,
            "仅支持 CSV/TSV/JSON/JSONL 表格或 XYZ/EXTXYZ/CIF/POSCAR/HDF5 结构来源入库，当前为 " + format);
      }
    } catch (ApiException ex) {
      throw ex;
    } catch (Exception ex) {
      throw new ApiException(HttpStatus.BAD_REQUEST,
          "读取来源数据失败: " + (ex.getMessage() == null ? ex.getClass().getSimpleName() : ex.getMessage()));
    }
    if (rows.isEmpty()) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "来源未解析出可入库的记录");
    }

    int written = displayDatasetService.ingestRecords(datasetKey, datasetName, rows);
    String message = "已半自动入库 " + written + " 条记录到展示库数据集 " + datasetKey
        + "（" + modeNote + "，写入前 " + written + " 条）。可在数据中心查看，后续仍需人工核对单位与完整性。";
    return applyStage(id, "PUBLISHED", message);
  }

  /** Withdraw a published ingest: remove its rows from the display DB and reset the stage. */
  public DatasetSubmissionResponse withdrawIngest(String authorization, long id) {
    authService.requireDatasetReviewAccess(authorization);
    findById(id); // 404 if the submission does not exist
    int removed = displayDatasetService.deleteDataset("intake_" + id);
    return applyStage(id, "VALIDATED",
        "已撤回入库：从展示库移除 " + removed + " 条记录，可重新入库。");
  }

  private DatasetSubmissionResponse applyStage(long id, String stage, String message) {
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DATASET_SUBMISSIONS
             SET PIPELINE_STAGE = ?, PIPELINE_MESSAGE = ?, UPDATED_AT = ?
             WHERE ID = ?
             """)) {
      statement.setString(1, stage);
      statement.setString(2, limitText(message, 1000));
      statement.setString(3, now);
      statement.setLong(4, id);
      statement.executeUpdate();
      return findById(id);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  private Map<String, String> suggestMapping(List<String> fields) {
    Map<String, String> mapping = new LinkedHashMap<>();
    for (String field : fields) {
      if (field == null || field.isBlank()) {
        continue;
      }
      String lower = field.toLowerCase(Locale.ROOT);
      putIfAbsentMatch(mapping, "SMILES", field, lower.contains("smiles"));
      putIfAbsentMatch(mapping, "MATERIAL_ID", field,
          lower.equals("id") || lower.contains("material_id") || lower.contains("mpid")
              || lower.contains("refcode") || lower.contains("identifier"));
      putIfAbsentMatch(mapping, "MATERIAL_NAME", field, lower.contains("name") || lower.contains("title"));
      putIfAbsentMatch(mapping, "COMPOSITION", field, lower.contains("formula") || lower.contains("composition"));
      putIfAbsentMatch(mapping, "ATOM_COUNT", field,
          lower.contains("natoms") || lower.equals("atoms") || lower.contains("atom_count") || lower.contains("n_atoms"));
      putIfAbsentMatch(mapping, "HOMO_LUMO_GAP", field, lower.contains("gap"));
      putIfAbsentMatch(mapping, "HOMO", field, lower.contains("homo") && !lower.contains("gap"));
      putIfAbsentMatch(mapping, "LUMO", field, lower.contains("lumo"));
      putIfAbsentMatch(mapping, "ENERGY", field,
          lower.contains("energy") && !lower.contains("homo") && !lower.contains("lumo") && !lower.contains("gap"));
      putIfAbsentMatch(mapping, "CHARGE", field, lower.contains("charge"));
      putIfAbsentMatch(mapping, "SPIN", field, lower.contains("spin") || lower.contains("multiplic"));
      putIfAbsentMatch(mapping, "CALCULATION_SOFTWARE", field,
          lower.contains("software") || lower.contains("functional") || lower.contains("method"));
      putIfAbsentMatch(mapping, "DOI", field, lower.contains("doi"));
    }
    return mapping;
  }

  private static void putIfAbsentMatch(Map<String, String> mapping, String target, String field, boolean match) {
    if (match && !mapping.containsKey(target)) {
      mapping.put(target, field);
    }
  }

  private List<Map<String, String>> extractTabularRecords(String format, DownloadSample sample, int limit) throws Exception {
    List<Map<String, String>> records = new ArrayList<>();
    if ("JSON".equals(format)) {
      JsonNode root = objectMapper.readTree(sample.bytes());
      JsonNode array = root.isArray() ? root
          : (root.path("data").isArray() ? root.path("data")
          : (root.path("records").isArray() ? root.path("records") : null));
      if (array != null) {
        for (JsonNode item : array) {
          if (records.size() >= limit) {
            break;
          }
          if (item.isObject()) {
            records.add(jsonObjectToRow(item));
          }
        }
      } else if (root.isObject()) {
        records.add(jsonObjectToRow(root));
      }
    } else if ("JSONL".equals(format)) {
      String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
      for (String line : lines) {
        if (records.size() >= limit) {
          break;
        }
        if (line.isBlank()) {
          continue;
        }
        JsonNode node = objectMapper.readTree(line);
        if (node.isObject()) {
          records.add(jsonObjectToRow(node));
        }
      }
    } else if ("CSV".equals(format) || "TSV".equals(format)) {
      String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
      if (lines.length >= 2) {
        String header = lines[0];
        String delimiter = "TSV".equals(format) ? "\t" : (header.contains("\t") ? "\t" : (header.contains(";") ? ";" : ","));
        List<String> columns = new ArrayList<>();
        for (String col : header.split(java.util.regex.Pattern.quote(delimiter))) {
          columns.add(col.trim().replaceAll("^\"|\"$", ""));
        }
        for (int i = 1; i < lines.length && records.size() < limit; i += 1) {
          if (lines[i].isBlank()) {
            continue;
          }
          String[] cells = lines[i].split(java.util.regex.Pattern.quote(delimiter));
          Map<String, String> row = new LinkedHashMap<>();
          for (int c = 0; c < columns.size() && c < cells.length; c += 1) {
            row.put(columns.get(c), cells[c].trim().replaceAll("^\"|\"$", ""));
          }
          records.add(row);
        }
      }
    }
    return records;
  }

  private static Map<String, String> jsonObjectToRow(JsonNode object) {
    Map<String, String> row = new LinkedHashMap<>();
    object.fields().forEachRemaining(entry -> {
      JsonNode value = entry.getValue();
      row.put(entry.getKey(), value.isValueNode() ? value.asText("") : value.toString());
    });
    return row;
  }

  private static boolean isStructureFormat(String format) {
    return "XYZ".equals(format) || "EXTXYZ".equals(format) || "CIF".equals(format)
        || "POSCAR".equals(format) || "HDF5".equals(format);
  }

  private static boolean isTabularFormat(String format) {
    return "JSON".equals(format) || "JSONL".equals(format) || "CSV".equals(format) || "TSV".equals(format);
  }

  private List<Map<String, String>> mapTabularRecords(
      List<Map<String, String>> sourceRecords, Map<String, String> mapping, String datasetKey, String datasetName) {
    List<Map<String, String>> rows = new ArrayList<>();
    int index = 0;
    for (Map<String, String> source : sourceRecords) {
      index += 1;
      Map<String, String> row = new LinkedHashMap<>();
      for (Map.Entry<String, String> entry : mapping.entrySet()) {
        String targetColumn = entry.getKey() == null ? "" : entry.getKey().trim().toUpperCase(Locale.ROOT);
        String sourceField = entry.getValue();
        if (targetColumn.isBlank() || sourceField == null || sourceField.isBlank()) {
          continue;
        }
        String value = source.get(sourceField);
        if (value != null) {
          row.put(targetColumn, value);
        }
      }
      if (!row.containsKey("SOURCE_RECORD_ID")) {
        row.put("SOURCE_RECORD_ID", datasetKey + "-" + index);
      }
      row.putIfAbsent("DATASET_NAME", datasetName);
      try {
        row.put("PROPERTIES_JSON", objectMapper.writeValueAsString(source));
      } catch (Exception ignored) {
        // Skip raw properties if it cannot be serialized.
      }
      rows.add(row);
    }
    return rows;
  }

  /**
   * Structure-format ingest adapter: turn CIF / (ext)XYZ / POSCAR samples into display
   * records with element/coordinate STRUCTURE_JSON plus derived ATOM_COUNT / COMPOSITION
   * (and ENERGY for extended XYZ). Geometry only; physical-property units still need a human.
   */
  private List<Map<String, String>> extractStructureRecords(
      String format, DownloadSample sample, int limit, String datasetKey, String datasetName) {
    return switch (format) {
      case "XYZ", "EXTXYZ" -> extractXyzRecords(sample, limit, datasetKey, datasetName);
      case "CIF" -> extractCifRecords(sample, datasetKey, datasetName);
      case "POSCAR" -> extractPoscarRecords(sample, datasetKey, datasetName);
      case "HDF5" -> extractHdf5Records(sample, limit, datasetKey, datasetName);
      default -> List.of();
    };
  }

  private List<Map<String, String>> extractXyzRecords(
      DownloadSample sample, int limit, String datasetKey, String datasetName) {
    List<Map<String, String>> rows = new ArrayList<>();
    String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
    int i = 0;
    int frame = 0;
    while (i < lines.length && rows.size() < limit) {
      String countLine = lines[i].trim();
      if (countLine.isEmpty()) {
        i += 1;
        continue;
      }
      int natoms;
      try {
        natoms = Integer.parseInt(countLine);
      } catch (NumberFormatException ex) {
        break; // Not a frame boundary; stop parsing.
      }
      int commentIdx = i + 1;
      int firstAtom = commentIdx + 1;
      if (natoms <= 0 || firstAtom + natoms > lines.length) {
        break; // Truncated final frame (sampled download) — stop cleanly.
      }
      String comment = commentIdx < lines.length ? lines[commentIdx] : "";
      int[] layout = xyzLayout(comment); // {posOffset, forceOffset(-1 if none)}
      int posOff = layout[0];
      int forceOff = layout[1];
      List<Map<String, Object>> atoms = new ArrayList<>();
      List<String> elements = new ArrayList<>();
      List<double[]> forces = new ArrayList<>();
      boolean allForces = forceOff >= 0;
      for (int a = 0; a < natoms && atoms.size() < 5000; a += 1) {
        String[] parts = lines[firstAtom + a].trim().split("\\s+");
        if (parts.length >= posOff + 3 && parts[0].matches("[A-Za-z]{1,2}\\d*")) {
          try {
            String element = parts[0].replaceAll("\\d", "");
            Map<String, Object> atom = new LinkedHashMap<>();
            atom.put("element", element);
            atom.put("x", Double.parseDouble(parts[posOff]));
            atom.put("y", Double.parseDouble(parts[posOff + 1]));
            atom.put("z", Double.parseDouble(parts[posOff + 2]));
            atoms.add(atom);
            elements.add(element);
            if (forceOff >= 0 && parts.length >= forceOff + 3) {
              forces.add(new double[] {
                  Double.parseDouble(parts[forceOff]),
                  Double.parseDouble(parts[forceOff + 1]),
                  Double.parseDouble(parts[forceOff + 2])});
            } else {
              allForces = false;
            }
          } catch (NumberFormatException ignored) {
            allForces = false; // Skip non-numeric coordinate/force rows.
          }
        }
      }
      frame += 1;
      if (!atoms.isEmpty()) {
        String energy = extractTagged(comment, "energy");
        Map<String, Object> structure = new LinkedHashMap<>();
        structure.put("format", "xyz");
        structure.put("atoms", atoms);
        double[][] lattice = parseXyzLattice(comment);
        if (lattice != null) {
          structure.put("lattice", latticeRows(lattice));
        }
        String stress = firstNonBlank(extractQuoted(comment, "stress"), extractQuoted(comment, "virial"));
        if (!stress.isBlank()) {
          structure.put("stress", stress);
        }
        Map<String, String> row = new LinkedHashMap<>();
        row.put("SOURCE_RECORD_ID", datasetKey + "-" + frame);
        row.put("DATASET_NAME", datasetName);
        row.put("MATERIAL_NAME", datasetName + " 结构 #" + frame);
        row.put("ATOM_COUNT", String.valueOf(atoms.size()));
        row.put("COMPOSITION", compositionOf(elements));
        if (!energy.isBlank()) {
          row.put("ENERGY", energy);
        }
        row.put("STRUCTURE_JSON", structureJson(structure));
        if (allForces && forces.size() == atoms.size()) {
          row.put("FORCES_JSON", forcesJson(forces));
        }
        rows.add(row);
      }
      i = firstAtom + natoms;
    }
    return rows;
  }

  private List<Map<String, String>> extractCifRecords(DownloadSample sample, String datasetKey, String datasetName) {
    String text = new String(sample.bytes(), StandardCharsets.UTF_8);
    String formula = "";
    for (String raw : text.split("\\r?\\n")) {
      String line = raw.trim();
      if (line.startsWith("_chemical_formula_sum")) {
        formula = line.substring("_chemical_formula_sum".length()).trim().replaceAll("['\"]", "");
      }
    }
    List<Map<String, Object>> atoms = parseCifAtoms(text);
    // Convert fractional coordinates to cartesian (Å) using the cell matrix so the 3D
    // viewer shows true geometry and can draw the periodic cell box.
    double[] cell = cifCell(text);
    double[][] matrix = cell != null ? cellMatrix(cell) : null;
    if (matrix != null) {
      for (Map<String, Object> atom : atoms) {
        double fx = asDouble(atom.get("x"));
        double fy = asDouble(atom.get("y"));
        double fz = asDouble(atom.get("z"));
        atom.put("x", round6(fx * matrix[0][0] + fy * matrix[1][0] + fz * matrix[2][0]));
        atom.put("y", round6(fx * matrix[0][1] + fy * matrix[1][1] + fz * matrix[2][1]));
        atom.put("z", round6(fx * matrix[0][2] + fy * matrix[1][2] + fz * matrix[2][2]));
      }
    }
    List<String> elements = new ArrayList<>();
    for (Map<String, Object> atom : atoms) {
      elements.add(String.valueOf(atom.get("element")));
    }
    String composition = !formula.isBlank() ? formula.replaceAll("\\s+", "") : compositionOf(elements);
    Map<String, Object> structure = new LinkedHashMap<>();
    structure.put("format", "cif");
    structure.put("coordinateType", matrix != null ? "cartesian" : "fractional");
    if (!formula.isBlank()) {
      structure.put("formula", formula);
    }
    if (!atoms.isEmpty()) {
      structure.put("atoms", atoms);
    }
    if (matrix != null) {
      structure.put("lattice", latticeRows(matrix));
    }
    Map<String, String> row = new LinkedHashMap<>();
    row.put("SOURCE_RECORD_ID", datasetKey + "-1");
    row.put("DATASET_NAME", datasetName);
    row.put("MATERIAL_NAME", datasetName + (composition.isBlank() ? " 晶体结构" : " · " + composition));
    if (!composition.isBlank()) {
      row.put("COMPOSITION", composition);
    }
    if (!atoms.isEmpty()) {
      row.put("ATOM_COUNT", String.valueOf(atoms.size()));
    }
    row.put("STRUCTURE_JSON", structureJson(structure));
    return List.of(row);
  }

  private List<Map<String, Object>> parseCifAtoms(String text) {
    List<Map<String, Object>> atoms = new ArrayList<>();
    String[] lines = text.split("\\r?\\n");
    int i = 0;
    while (i < lines.length) {
      if (lines[i].trim().equalsIgnoreCase("loop_")) {
        List<String> headers = new ArrayList<>();
        int j = i + 1;
        while (j < lines.length && lines[j].trim().startsWith("_")) {
          headers.add(lines[j].trim());
          j += 1;
        }
        int xi = headers.indexOf("_atom_site_fract_x");
        int yi = headers.indexOf("_atom_site_fract_y");
        int zi = headers.indexOf("_atom_site_fract_z");
        int si = headers.indexOf("_atom_site_type_symbol");
        if (si < 0) {
          si = headers.indexOf("_atom_site_label");
        }
        if (xi >= 0 && yi >= 0 && zi >= 0 && si >= 0) {
          for (int k = j; k < lines.length; k += 1) {
            String row = lines[k].trim();
            if (row.isEmpty() || row.startsWith("_") || row.equalsIgnoreCase("loop_") || row.startsWith("#")) {
              break;
            }
            String[] cells = row.split("\\s+");
            if (cells.length > Math.max(Math.max(xi, yi), Math.max(zi, si)) && atoms.size() < 5000) {
              try {
                Map<String, Object> atom = new LinkedHashMap<>();
                atom.put("element", cells[si].replaceAll("[^A-Za-z]", ""));
                // Fractional coordinates stored under x/y/z so the structure renderer picks them up.
                atom.put("x", Double.parseDouble(cells[xi].replaceAll("\\(.*\\)", "")));
                atom.put("y", Double.parseDouble(cells[yi].replaceAll("\\(.*\\)", "")));
                atom.put("z", Double.parseDouble(cells[zi].replaceAll("\\(.*\\)", "")));
                atoms.add(atom);
              } catch (NumberFormatException ignored) {
                // Skip malformed atom row.
              }
            }
          }
          return atoms;
        }
        i = j;
      } else {
        i += 1;
      }
    }
    return atoms;
  }

  private List<Map<String, String>> extractPoscarRecords(DownloadSample sample, String datasetKey, String datasetName) {
    String[] lines = new String(sample.bytes(), StandardCharsets.UTF_8).split("\\r?\\n");
    if (lines.length < 7) {
      return List.of();
    }
    List<String> species = new ArrayList<>();
    for (String s : lines[5].trim().split("\\s+")) {
      if (s.matches("[A-Z][a-z]?")) {
        species.add(s);
      }
    }
    List<Integer> counts = new ArrayList<>();
    for (String c : lines[6].trim().split("\\s+")) {
      try {
        counts.add(Integer.parseInt(c));
      } catch (NumberFormatException ignored) {
        // ignore
      }
    }
    List<String> elements = new ArrayList<>();
    for (int s = 0; s < species.size() && s < counts.size(); s += 1) {
      for (int n = 0; n < counts.get(s); n += 1) {
        elements.add(species.get(s));
      }
    }
    Map<String, Object> structure = new LinkedHashMap<>();
    structure.put("format", "poscar");
    structure.put("species", species);
    structure.put("counts", counts);
    String composition = compositionOf(elements);
    Map<String, String> row = new LinkedHashMap<>();
    row.put("SOURCE_RECORD_ID", datasetKey + "-1");
    row.put("DATASET_NAME", datasetName);
    row.put("MATERIAL_NAME", datasetName + (composition.isBlank() ? " 结构" : " · " + composition));
    if (!composition.isBlank()) {
      row.put("COMPOSITION", composition);
    }
    if (!elements.isEmpty()) {
      row.put("ATOM_COUNT", String.valueOf(elements.size()));
    }
    row.put("STRUCTURE_JSON", structureJson(structure));
    return List.of(row);
  }

  private List<Map<String, String>> extractHdf5Records(
      DownloadSample sample, int limit, String datasetKey, String datasetName) {
    if (sample.truncated()) {
      throw new ApiException(HttpStatus.BAD_REQUEST,
          "HDF5 文件被 Range 抽样截断，不能安全解析结构；请调高 vasp.intake.discovery.auto-adapt.max-download-mb，或人工下载完整文件后再入库。");
    }
    Path temp = null;
    try {
      temp = Files.createTempFile("vasp-ingest-hdf5-", ".h5");
      Files.write(temp, sample.bytes());
      try (HdfFile hdf = new HdfFile(temp)) {
        List<Hdf5GroupCandidate> candidates = new ArrayList<>();
        collectHdf5Candidates(hdf, "", candidates);
        List<Map<String, String>> rows = new ArrayList<>();
        for (Hdf5GroupCandidate candidate : candidates) {
          appendHdf5CandidateRows(candidate, rows, limit, datasetKey, datasetName);
          if (rows.size() >= limit) {
            break;
          }
        }
        return rows;
      }
    } catch (ApiException ex) {
      throw ex;
    } catch (Exception ex) {
      throw new ApiException(HttpStatus.BAD_REQUEST,
          "HDF5 结构解析失败: " + (ex.getMessage() == null ? ex.getClass().getSimpleName() : ex.getMessage()));
    } finally {
      if (temp != null) {
        try {
          Files.deleteIfExists(temp);
        } catch (Exception ignored) {
          // best-effort cleanup
        }
      }
    }
  }

  private void collectHdf5Candidates(Group group, String path, List<Hdf5GroupCandidate> candidates) {
    Dataset coordinates = bestDirectDataset(group, this::isCoordinateDataset);
    Dataset atomLabels = bestDirectDataset(group, this::isAtomLabelDataset);
    if (coordinates != null && atomLabels != null) {
      candidates.add(new Hdf5GroupCandidate(
          path.isBlank() ? "/" : path,
          coordinates,
          atomLabels,
          bestDirectDataset(group, this::isEnergyDataset),
          bestDirectDataset(group, this::isForceDataset),
          bestDirectDataset(group, this::isLatticeDataset)
      ));
    }
    for (Map.Entry<String, Node> entry : group.getChildren().entrySet()) {
      if (entry.getValue() instanceof Group child) {
        String childPath = path + "/" + entry.getKey();
        collectHdf5Candidates(child, childPath, candidates);
      }
    }
  }

  private Dataset bestDirectDataset(Group group, DatasetPredicate predicate) {
    Dataset best = null;
    int bestScore = Integer.MIN_VALUE;
    for (Map.Entry<String, Node> entry : group.getChildren().entrySet()) {
      if (entry.getValue() instanceof Dataset dataset && predicate.test(entry.getKey(), dataset)) {
        int score = datasetNameScore(entry.getKey());
        if (score > bestScore) {
          best = dataset;
          bestScore = score;
        }
      }
    }
    return best;
  }

  private boolean isCoordinateDataset(String name, Dataset dataset) {
    int[] dims = dataset.getDimensions();
    if (dims.length < 2 || dims[dims.length - 1] != 3 || hasZeroDimension(dims)) {
      return false;
    }
    String key = name.toLowerCase(Locale.ROOT);
    return key.contains("coordinate") || key.contains("position") || key.contains("coords")
        || key.equals("pos") || key.equals("xyz") || key.equals("r");
  }

  private boolean isAtomLabelDataset(String name, Dataset dataset) {
    int[] dims = dataset.getDimensions();
    if (dims.length == 0 || hasZeroDimension(dims)) {
      return false;
    }
    String key = name.toLowerCase(Locale.ROOT);
    return key.contains("species") || key.contains("atomic_number") || key.contains("atomicnumber")
        || key.contains("numbers") || key.contains("elements") || key.contains("symbols") || key.equals("z");
  }

  private boolean isEnergyDataset(String name, Dataset dataset) {
    int[] dims = dataset.getDimensions();
    String key = name.toLowerCase(Locale.ROOT);
    return !hasZeroDimension(dims) && (key.equals("energy") || key.equals("energies")
        || key.contains("total_energy") || key.endsWith(".energy"));
  }

  private boolean isForceDataset(String name, Dataset dataset) {
    int[] dims = dataset.getDimensions();
    String key = name.toLowerCase(Locale.ROOT);
    return !hasZeroDimension(dims) && dims.length >= 2 && dims[dims.length - 1] == 3
        && (key.contains("force") || key.equals("f"));
  }

  private boolean isLatticeDataset(String name, Dataset dataset) {
    int[] dims = dataset.getDimensions();
    String key = name.toLowerCase(Locale.ROOT);
    return !hasZeroDimension(dims) && dims.length >= 2 && dims[dims.length - 1] == 3
        && (key.contains("lattice") || key.equals("cell") || key.contains("cell_vectors"));
  }

  private static boolean hasZeroDimension(int[] dims) {
    for (int dim : dims) {
      if (dim <= 0) {
        return true;
      }
    }
    return false;
  }

  private static int datasetNameScore(String name) {
    String key = name.toLowerCase(Locale.ROOT);
    if (key.equals("coordinates") || key.equals("positions") || key.equals("species")
        || key.equals("atomic_numbers") || key.equals("energies") || key.equals("forces")) {
      return 100;
    }
    if (key.contains("he") || key.contains("high")) {
      return -10;
    }
    return 0;
  }

  private void appendHdf5CandidateRows(
      Hdf5GroupCandidate candidate,
      List<Map<String, String>> rows,
      int limit,
      String datasetKey,
      String datasetName
  ) {
    int[] coordDims = candidate.coordinates().getDimensions();
    int atomCount = coordDims[coordDims.length - 2];
    int conformerCount = coordDims.length >= 3 ? coordDims[0] : 1;
    List<Double> coordinates = flattenNumbers(candidate.coordinates().getDataFlat());
    List<Hdf5AtomLabel> labels = readHdf5AtomLabels(candidate.atomLabels(), atomCount);
    if (labels.size() < atomCount || coordinates.size() < (long) conformerCount * atomCount * 3L) {
      return;
    }
    List<Double> energies = candidate.energies() == null ? List.of() : flattenNumbers(candidate.energies().getDataFlat());
    List<Double> forces = candidate.forces() == null ? List.of() : flattenNumbers(candidate.forces().getDataFlat());
    List<Double> lattice = candidate.lattice() == null ? List.of() : flattenNumbers(candidate.lattice().getDataFlat());
    int max = Math.min(conformerCount, Math.max(0, limit - rows.size()));
    for (int conf = 0; conf < max; conf += 1) {
      List<Map<String, Object>> atoms = new ArrayList<>();
      List<String> elements = new ArrayList<>();
      long offset = (long) conf * atomCount * 3L;
      for (int atomIndex = 0; atomIndex < atomCount; atomIndex += 1) {
        int base = (int) offset + atomIndex * 3;
        Hdf5AtomLabel label = labels.get(atomIndex);
        Map<String, Object> atom = new LinkedHashMap<>();
        if (!label.element().isBlank()) {
          atom.put("element", label.element());
          elements.add(label.element());
        }
        if (label.atomicNumber() > 0) {
          atom.put("atomic_number", label.atomicNumber());
          if (label.element().isBlank()) {
            String element = elementByAtomicNumber(label.atomicNumber());
            if (!element.isBlank()) {
              elements.add(element);
            }
          }
        }
        atom.put("x", round6(coordinates.get(base)));
        atom.put("y", round6(coordinates.get(base + 1)));
        atom.put("z", round6(coordinates.get(base + 2)));
        atoms.add(atom);
      }
      Map<String, Object> structure = new LinkedHashMap<>();
      structure.put("format", "hdf5");
      structure.put("sourceGroup", candidate.path());
      structure.put("conformerIndex", conf);
      structure.put("atoms", atoms);
      List<List<Double>> latticeRows = hdf5LatticeRows(lattice, candidate.lattice() == null ? new int[0] : candidate.lattice().getDimensions(), conf);
      if (!latticeRows.isEmpty()) {
        structure.put("lattice", latticeRows);
      }

      Map<String, String> row = new LinkedHashMap<>();
      row.put("SOURCE_RECORD_ID", datasetKey + "-" + sanitizeId(candidate.path()) + "#" + conf);
      row.put("DATASET_NAME", datasetName);
      row.put("MATERIAL_NAME", datasetName + " " + candidate.path() + " 构型 " + (conf + 1));
      row.put("ATOM_COUNT", String.valueOf(atomCount));
      String composition = compositionOf(elements);
      if (!composition.isBlank()) {
        row.put("COMPOSITION", composition);
      }
      if (conf < energies.size()) {
        row.put("ENERGY", String.valueOf(energies.get(conf)));
      }
      row.put("STRUCTURE_JSON", structureJson(structure));
      String forcesJson = hdf5ForcesJson(forces, candidate.forces() == null ? new int[0] : candidate.forces().getDimensions(), conf, atomCount);
      if (!forcesJson.isBlank()) {
        row.put("FORCES_JSON", forcesJson);
      }
      rows.add(row);
      if (rows.size() >= limit) {
        break;
      }
    }
  }

  private List<Hdf5AtomLabel> readHdf5AtomLabels(Dataset dataset, int atomCount) {
    String name = dataset.getName().toLowerCase(Locale.ROOT);
    List<Double> numbers = flattenNumbers(dataset.getDataFlat());
    if ((name.contains("number") || name.equals("z")) && numbers.size() >= atomCount) {
      List<Hdf5AtomLabel> labels = new ArrayList<>();
      for (int i = 0; i < atomCount; i += 1) {
        int z = (int) Math.round(numbers.get(i));
        labels.add(new Hdf5AtomLabel(elementByAtomicNumber(z), z));
      }
      return labels;
    }
    List<String> symbols = flattenTextItems(dataset.getData(), atomCount);
    if (symbols.size() >= atomCount) {
      List<Hdf5AtomLabel> labels = new ArrayList<>();
      for (int i = 0; i < atomCount; i += 1) {
        String symbol = normalizeElementSymbol(symbols.get(i));
        labels.add(new Hdf5AtomLabel(symbol, atomicNumberFor(symbol)));
      }
      return labels;
    }
    return List.of();
  }

  private List<List<Double>> hdf5LatticeRows(List<Double> values, int[] dims, int conformerIndex) {
    if (values.size() < 9 || dims.length < 2) {
      return List.of();
    }
    int offset = dims.length >= 3 ? conformerIndex * 9 : 0;
    if (values.size() < offset + 9) {
      return List.of();
    }
    double[][] matrix = new double[][] {
        {round6(values.get(offset)), round6(values.get(offset + 1)), round6(values.get(offset + 2))},
        {round6(values.get(offset + 3)), round6(values.get(offset + 4)), round6(values.get(offset + 5))},
        {round6(values.get(offset + 6)), round6(values.get(offset + 7)), round6(values.get(offset + 8))}
    };
    return latticeRows(matrix);
  }

  private String hdf5ForcesJson(List<Double> values, int[] dims, int conformerIndex, int atomCount) {
    if (values.size() < atomCount * 3L || dims.length < 2 || dims[dims.length - 1] != 3) {
      return "";
    }
    int offset = dims.length >= 3 ? conformerIndex * atomCount * 3 : 0;
    if (values.size() < offset + atomCount * 3) {
      return "";
    }
    List<double[]> forces = new ArrayList<>();
    for (int atom = 0; atom < atomCount; atom += 1) {
      int base = offset + atom * 3;
      forces.add(new double[] {values.get(base), values.get(base + 1), values.get(base + 2)});
    }
    return forcesJson(forces);
  }

  private static String sanitizeId(String value) {
    String raw = value == null || value.isBlank() ? "root" : value;
    return raw.replaceAll("[^A-Za-z0-9._-]+", "_").replaceAll("^_+|_+$", "");
  }

  private static List<Double> flattenNumbers(Object data) {
    List<Double> values = new ArrayList<>();
    collectNumbers(data, values);
    return values;
  }

  private static void collectNumbers(Object value, List<Double> values) {
    if (value == null) {
      return;
    }
    if (value instanceof Number number) {
      values.add(number.doubleValue());
      return;
    }
    Class<?> type = value.getClass();
    if (type.isArray()) {
      int length = Array.getLength(value);
      for (int i = 0; i < length; i += 1) {
        collectNumbers(Array.get(value, i), values);
      }
    }
  }

  private static List<String> flattenTextItems(Object data, int expectedCount) {
    List<String> values = new ArrayList<>();
    collectTextItems(data, values, expectedCount);
    return values.stream()
        .map(String::trim)
        .filter(value -> !value.isBlank())
        .toList();
  }

  private static void collectTextItems(Object value, List<String> values, int expectedCount) {
    if (value == null) {
      return;
    }
    if (value instanceof String string) {
      values.add(string);
      return;
    }
    if (value instanceof Character character) {
      values.add(Character.toString(character));
      return;
    }
    if (value instanceof Byte byteValue) {
      int unsigned = Byte.toUnsignedInt(byteValue);
      if (unsigned != 0) {
        values.add(Character.toString((char) unsigned));
      }
      return;
    }
    Class<?> type = value.getClass();
    if (type.isArray()) {
      int length = Array.getLength(value);
      if (isByteLikeArray(value)) {
        if (length == expectedCount && expectedCount > 1) {
          for (int i = 0; i < length; i += 1) {
            collectTextItems(Array.get(value, i), values, expectedCount);
          }
        } else {
          String text = byteLikeArrayToString(value);
          if (!text.isBlank()) {
            values.add(text);
          }
        }
        return;
      }
      for (int i = 0; i < length; i += 1) {
        collectTextItems(Array.get(value, i), values, expectedCount);
      }
    }
  }

  private static boolean isByteLikeArray(Object value) {
    Class<?> component = value.getClass().getComponentType();
    return component == byte.class || component == Byte.class || component == char.class || component == Character.class;
  }

  private static String byteLikeArrayToString(Object value) {
    StringBuilder builder = new StringBuilder();
    int length = Array.getLength(value);
    for (int i = 0; i < length; i += 1) {
      Object item = Array.get(value, i);
      char ch = 0;
      if (item instanceof Byte b) {
        ch = (char) Byte.toUnsignedInt(b);
      } else if (item instanceof Character c) {
        ch = c;
      }
      if (ch != 0) {
        builder.append(ch);
      }
    }
    return builder.toString().trim();
  }

  private static String normalizeElementSymbol(String raw) {
    String clean = raw == null ? "" : raw.replaceAll("[^A-Za-z]", "");
    if (clean.isBlank()) {
      return "";
    }
    if (clean.length() == 1) {
      return clean.toUpperCase(Locale.ROOT);
    }
    return clean.substring(0, 1).toUpperCase(Locale.ROOT) + clean.substring(1, Math.min(clean.length(), 2)).toLowerCase(Locale.ROOT);
  }

  private static String elementByAtomicNumber(int z) {
    return switch (z) {
      case 1 -> "H";
      case 2 -> "He";
      case 3 -> "Li";
      case 4 -> "Be";
      case 5 -> "B";
      case 6 -> "C";
      case 7 -> "N";
      case 8 -> "O";
      case 9 -> "F";
      case 10 -> "Ne";
      case 11 -> "Na";
      case 12 -> "Mg";
      case 13 -> "Al";
      case 14 -> "Si";
      case 15 -> "P";
      case 16 -> "S";
      case 17 -> "Cl";
      case 18 -> "Ar";
      case 19 -> "K";
      case 20 -> "Ca";
      case 21 -> "Sc";
      case 22 -> "Ti";
      case 23 -> "V";
      case 24 -> "Cr";
      case 25 -> "Mn";
      case 26 -> "Fe";
      case 27 -> "Co";
      case 28 -> "Ni";
      case 29 -> "Cu";
      case 30 -> "Zn";
      case 35 -> "Br";
      case 47 -> "Ag";
      case 48 -> "Cd";
      case 53 -> "I";
      default -> "";
    };
  }

  private static int atomicNumberFor(String symbol) {
    return switch (symbol) {
      case "H" -> 1;
      case "He" -> 2;
      case "Li" -> 3;
      case "Be" -> 4;
      case "B" -> 5;
      case "C" -> 6;
      case "N" -> 7;
      case "O" -> 8;
      case "F" -> 9;
      case "Ne" -> 10;
      case "Na" -> 11;
      case "Mg" -> 12;
      case "Al" -> 13;
      case "Si" -> 14;
      case "P" -> 15;
      case "S" -> 16;
      case "Cl" -> 17;
      case "Ar" -> 18;
      case "K" -> 19;
      case "Ca" -> 20;
      case "Sc" -> 21;
      case "Ti" -> 22;
      case "V" -> 23;
      case "Cr" -> 24;
      case "Mn" -> 25;
      case "Fe" -> 26;
      case "Co" -> 27;
      case "Ni" -> 28;
      case "Cu" -> 29;
      case "Zn" -> 30;
      case "Br" -> 35;
      case "Ag" -> 47;
      case "Cd" -> 48;
      case "I" -> 53;
      default -> 0;
    };
  }

  private static double asDouble(Object value) {
    return value instanceof Number number ? number.doubleValue() : 0.0;
  }

  private static double round6(double value) {
    return Math.round(value * 1_000_000d) / 1_000_000d;
  }

  /** Parse CIF cell parameters {a,b,c,alpha,beta,gamma}; null if any is missing/invalid. */
  private static double[] cifCell(String text) {
    Double a = cifNumber(text, "_cell_length_a");
    Double b = cifNumber(text, "_cell_length_b");
    Double c = cifNumber(text, "_cell_length_c");
    Double alpha = cifNumber(text, "_cell_angle_alpha");
    Double beta = cifNumber(text, "_cell_angle_beta");
    Double gamma = cifNumber(text, "_cell_angle_gamma");
    if (a == null || b == null || c == null || alpha == null || beta == null || gamma == null) {
      return null;
    }
    if (a <= 0 || b <= 0 || c <= 0) {
      return null;
    }
    return new double[] {a, b, c, alpha, beta, gamma};
  }

  private static Double cifNumber(String text, String tag) {
    for (String raw : text.split("\\r?\\n")) {
      String line = raw.trim();
      if (line.startsWith(tag)
          && (line.length() == tag.length() || Character.isWhitespace(line.charAt(tag.length())))) {
        String rest = line.substring(tag.length()).replaceAll("\\(.*?\\)", "").trim();
        String first = rest.split("\\s+")[0];
        try {
          return Double.parseDouble(first);
        } catch (NumberFormatException ex) {
          return null;
        }
      }
    }
    return null;
  }

  /** Build the cartesian lattice matrix (rows = a,b,c vectors in Å) from cell parameters. */
  private static double[][] cellMatrix(double[] cell) {
    double a = cell[0];
    double b = cell[1];
    double c = cell[2];
    double alpha = Math.toRadians(cell[3]);
    double beta = Math.toRadians(cell[4]);
    double gamma = Math.toRadians(cell[5]);
    double cosA = Math.cos(alpha);
    double cosB = Math.cos(beta);
    double cosG = Math.cos(gamma);
    double sinG = Math.sin(gamma);
    double bx = b * cosG;
    double by = b * sinG;
    double cx = c * cosB;
    double cy = sinG == 0 ? 0 : c * (cosA - cosB * cosG) / sinG;
    double volume = 1 - cosA * cosA - cosB * cosB - cosG * cosG + 2 * cosA * cosB * cosG;
    double cz = sinG == 0 ? 0 : c * Math.sqrt(Math.max(volume, 0)) / sinG;
    return new double[][] {
        {round6(a), 0.0, 0.0},
        {round6(bx), round6(by), 0.0},
        {round6(cx), round6(cy), round6(cz)}
    };
  }

  private static List<List<Double>> latticeRows(double[][] matrix) {
    List<List<Double>> rows = new ArrayList<>();
    for (double[] row : matrix) {
      rows.add(List.of(row[0], row[1], row[2]));
    }
    return rows;
  }

  /** Locate position/force column offsets from an extended-XYZ {@code Properties=} spec. */
  private static int[] xyzLayout(String comment) {
    int posOffset = 1; // default simple xyz: element then x y z
    int forceOffset = -1;
    if (comment != null) {
      java.util.regex.Matcher m = java.util.regex.Pattern
          .compile("(?i)Properties\\s*=\\s*(?:\"([^\"]*)\"|(\\S+))").matcher(comment);
      if (m.find()) {
        String spec = m.group(1) != null ? m.group(1) : m.group(2);
        String[] tokens = spec.split(":");
        int cursor = 0;
        for (int t = 0; t + 2 < tokens.length; t += 3) {
          String name = tokens[t].toLowerCase(Locale.ROOT);
          int count;
          try {
            count = Integer.parseInt(tokens[t + 2]);
          } catch (NumberFormatException ex) {
            count = 1;
          }
          if (name.equals("pos") || name.equals("positions") || name.equals("r")) {
            posOffset = cursor;
          } else if (name.equals("forces") || name.equals("force") || name.equals("f")) {
            forceOffset = cursor;
          }
          cursor += count;
        }
      }
    }
    return new int[] {posOffset, forceOffset};
  }

  private static double[][] parseXyzLattice(String comment) {
    String latStr = extractQuoted(comment, "Lattice");
    if (latStr.isBlank()) {
      return null;
    }
    String[] p = latStr.trim().split("\\s+");
    if (p.length < 9) {
      return null;
    }
    try {
      double[] v = new double[9];
      for (int k = 0; k < 9; k += 1) {
        v[k] = round6(Double.parseDouble(p[k]));
      }
      return new double[][] {{v[0], v[1], v[2]}, {v[3], v[4], v[5]}, {v[6], v[7], v[8]}};
    } catch (NumberFormatException ex) {
      return null;
    }
  }

  private String forcesJson(List<double[]> forces) {
    List<List<Double>> out = new ArrayList<>();
    for (double[] f : forces) {
      out.add(List.of(round6(f[0]), round6(f[1]), round6(f[2])));
    }
    try {
      return limitText(objectMapper.writeValueAsString(out), 40000);
    } catch (Exception ex) {
      return "";
    }
  }

  private static String firstNonBlank(String... values) {
    for (String value : values) {
      if (value != null && !value.isBlank()) {
        return value.trim();
      }
    }
    return "";
  }

  private String structureJson(Map<String, Object> structure) {
    try {
      return limitText(objectMapper.writeValueAsString(structure), 40000);
    } catch (Exception ex) {
      return "";
    }
  }

  /** Hill-system composition string (C, then H, then other elements alphabetically). */
  private static String compositionOf(List<String> elements) {
    Map<String, Integer> counts = new java.util.TreeMap<>();
    for (String element : elements) {
      if (element != null && !element.isBlank()) {
        counts.merge(element, 1, Integer::sum);
      }
    }
    if (counts.isEmpty()) {
      return "";
    }
    StringBuilder sb = new StringBuilder();
    appendElement(sb, "C", counts.remove("C"));
    appendElement(sb, "H", counts.remove("H"));
    for (Map.Entry<String, Integer> entry : counts.entrySet()) {
      appendElement(sb, entry.getKey(), entry.getValue());
    }
    return sb.toString();
  }

  private static void appendElement(StringBuilder sb, String element, Integer count) {
    if (count == null || count <= 0) {
      return;
    }
    sb.append(element);
    if (count > 1) {
      sb.append(count);
    }
  }

  private static String extractTagged(String text, String key) {
    if (text == null) {
      return "";
    }
    java.util.regex.Matcher m = java.util.regex.Pattern
        .compile("(?i)\\b" + key + "\\s*=\\s*(-?\\d+(?:\\.\\d+)?(?:[eE][+-]?\\d+)?)")
        .matcher(text);
    return m.find() ? m.group(1) : "";
  }

  private static String extractQuoted(String text, String key) {
    if (text == null) {
      return "";
    }
    java.util.regex.Matcher m = java.util.regex.Pattern
        .compile("(?i)\\b" + key + "\\s*=\\s*\"([^\"]*)\"")
        .matcher(text);
    return m.find() ? m.group(1) : "";
  }

  private DatasetSubmissionResponse findById(long id) {
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(
             "SELECT * FROM DATASET_SUBMISSIONS WHERE ID = ?")) {
      statement.setLong(1, id);
      try (ResultSet rs = statement.executeQuery()) {
        if (!rs.next()) {
          throw new ApiException(HttpStatus.NOT_FOUND, "找不到数据集投稿: " + id);
        }
        return fromResult(rs);
      }
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  private DatasetSubmissionResponse fromResult(ResultSet rs) throws SQLException {
    return new DatasetSubmissionResponse(
        rs.getLong("ID"),
        rs.getString("DATASET_NAME"),
        rs.getString("DATA_TYPE"),
        rs.getString("DESCRIPTION"),
        rs.getString("PAPER_URL"),
        rs.getString("DATA_URL"),
        rs.getString("DATA_FORMAT"),
        rs.getString("LICENSE_TEXT"),
        rs.getString("PROVIDED_FIELDS"),
        rs.getString("SUBMITTED_BY"),
        rs.getString("SUBMITTED_AT"),
        rs.getString("STATUS"),
        rs.getString("REVIEW_NOTE"),
        rs.getString("REVIEWED_AT"),
        rs.getString("PIPELINE_STAGE"),
        rs.getString("PIPELINE_MESSAGE"),
        rs.getString("UPDATED_AT"),
        rs.getString("PARSE_PROFILE")
    );
  }

  private String normalizeDecision(String value) {
    String decision = value == null ? "" : value.trim().toUpperCase(Locale.ROOT);
    if (!"APPROVED".equals(decision) && !"REJECTED".equals(decision)) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "审核决定仅支持 APPROVED 或 REJECTED");
    }
    return decision;
  }

  private String required(String value, String label, int maxLength) {
    String text = optional(value, maxLength);
    if (text.isBlank()) {
      throw new ApiException(HttpStatus.BAD_REQUEST, label + "不能为空");
    }
    return text;
  }

  private String optional(String value, int maxLength) {
    String text = value == null ? "" : value.trim();
    if (text.length() > maxLength) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "输入内容过长");
    }
    return text;
  }

  private String optionalUrl(String value, String label) {
    String url = optional(value, 500);
    if (url.isBlank()) {
      return "";
    }
    try {
      URI uri = URI.create(url);
      if (!"https".equalsIgnoreCase(uri.getScheme()) && !"http".equalsIgnoreCase(uri.getScheme())) {
        throw new IllegalArgumentException();
      }
    } catch (IllegalArgumentException ex) {
      throw new ApiException(HttpStatus.BAD_REQUEST, label + "必须为 http/https 地址");
    }
    return url;
  }

  private Connection openConnection() throws SQLException {
    return DriverManager.getConnection(resolveJdbcUrl(), "sa", "");
  }

  private String resolveJdbcUrl() {
    String cached = jdbcUrl;
    if (cached != null) {
      return cached;
    }
    synchronized (this) {
      if (jdbcUrl == null) {
        Path path = Paths.get(properties.getDbPath());
        Path cwd = Paths.get("").toAbsolutePath();
        Path candidate = path.isAbsolute() ? path : cwd.resolve(path).normalize();
        Path projectCandidate = path.isAbsolute() ? path : cwd.resolve("..").resolve(path).normalize();
        if (!path.isAbsolute() && Files.isDirectory(projectCandidate.getParent())) {
          candidate = projectCandidate;
        }
        try {
          Files.createDirectories(candidate.toAbsolutePath().getParent());
        } catch (Exception ex) {
          throw new IllegalStateException("创建数据接入数据库目录失败: " + ex.getMessage(), ex);
        }
        String normalized = candidate.toAbsolutePath().normalize().toString().replace('\\', '/');
        jdbcUrl = "jdbc:h2:" + normalized;
      }
      return jdbcUrl;
    }
  }

  private static ApiException databaseError(SQLException ex) {
    return new ApiException(HttpStatus.INTERNAL_SERVER_ERROR, "读取数据接入数据库失败: " + ex.getMessage());
  }
}
