package com.vaspshow.backend.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.vaspshow.backend.config.IntakeProperties;
import com.vaspshow.backend.dto.DatasetSubmissionRequest;
import com.vaspshow.backend.dto.DatasetSubmissionResponse;
import com.vaspshow.backend.dto.DiscoveryCandidateResponse;
import com.vaspshow.backend.dto.DiscoveryConfigResponse;
import com.vaspshow.backend.dto.DiscoveryConfigUpdateRequest;
import com.vaspshow.backend.dto.DiscoveryDecisionRequest;
import com.vaspshow.backend.dto.DiscoveryRunResponse;
import com.vaspshow.backend.dto.DiscoverySourceResponse;
import com.vaspshow.backend.dto.DiscoverySourceStat;
import com.vaspshow.backend.dto.ValidationCheck;
import com.vaspshow.backend.dto.ValidationReport;
import com.vaspshow.backend.exception.ApiException;
import com.vaspshow.backend.support.OutboundUrlGuard;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import org.springframework.http.HttpStatus;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class DatasetDiscoveryService {

  private static final int SAMPLE_BYTES = 256 * 1024;

  /** Advisory floor used only in recommendation text to flag likely cross-domain noise. */
  private static final int RELEVANCE_NOISE_FLOOR = 44;

  private final IntakeProperties properties;
  private final AuthService authService;
  private final DatasetIntakeService intakeService;
  private final DatasetValidationService validationService;
  private final ObjectMapper objectMapper;
  private final ExecutorService discoveryExecutor = Executors.newSingleThreadExecutor(runnable -> {
    Thread thread = new Thread(runnable, "vasp-dataset-discovery");
    thread.setDaemon(true);
    return thread;
  });
  private final HttpClient httpClient = HttpClient.newBuilder()
      .connectTimeout(Duration.ofSeconds(8))
      .followRedirects(HttpClient.Redirect.NORMAL)
      .build();
  private volatile String jdbcUrl;
  private final AtomicBoolean running = new AtomicBoolean(false);

  public DatasetDiscoveryService(
      IntakeProperties properties,
      AuthService authService,
      DatasetIntakeService intakeService,
      DatasetValidationService validationService,
      ObjectMapper objectMapper
  ) {
    this.properties = properties;
    this.authService = authService;
    this.intakeService = intakeService;
    this.validationService = validationService;
    this.objectMapper = objectMapper;
  }

  @PostConstruct
  public void initialize() {
    try (Connection connection = openConnection();
         Statement statement = connection.createStatement()) {
      statement.execute("""
          CREATE TABLE IF NOT EXISTS DISCOVERY_CANDIDATES (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            SOURCE VARCHAR(80) NOT NULL,
            TITLE VARCHAR(500) NOT NULL,
            DOI VARCHAR(180) NOT NULL,
            PAPER_URL VARCHAR(500) NOT NULL,
            DATA_URL VARCHAR(500) NOT NULL,
            REPOSITORY VARCHAR(120) NOT NULL,
            LICENSE_TEXT VARCHAR(180) NOT NULL,
            DATA_FORMAT VARCHAR(80) NOT NULL,
            DATA_SCALE VARCHAR(120) NOT NULL,
            METHOD_TEXT VARCHAR(180) NOT NULL,
            DETECTED_FIELDS VARCHAR(800) NOT NULL,
            PARSER_PLAN VARCHAR(500) NOT NULL,
            SCORE INT NOT NULL,
            RELEVANCE INT DEFAULT 0 NOT NULL,
            VALIDATION_STATUS VARCHAR(16) DEFAULT '' NOT NULL,
            VALIDATION_JSON VARCHAR(4000) DEFAULT '' NOT NULL,
            VALIDATED_AT VARCHAR(40) DEFAULT '' NOT NULL,
            RECOMMENDATION VARCHAR(1000) NOT NULL,
            STATUS VARCHAR(32) NOT NULL,
            REVIEW_NOTE VARCHAR(1000) NOT NULL,
            DISCOVERED_AT VARCHAR(40) NOT NULL,
            UPDATED_AT VARCHAR(40) NOT NULL,
            UNIQUE_KEY VARCHAR(640) NOT NULL
          )
          """);
      statement.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_discovery_unique ON DISCOVERY_CANDIDATES(UNIQUE_KEY)");
      statement.execute("CREATE INDEX IF NOT EXISTS idx_discovery_status ON DISCOVERY_CANDIDATES(STATUS, SCORE)");
      statement.execute("ALTER TABLE DISCOVERY_CANDIDATES ADD COLUMN IF NOT EXISTS RELEVANCE INT DEFAULT 0 NOT NULL");
      statement.execute("ALTER TABLE DISCOVERY_CANDIDATES ADD COLUMN IF NOT EXISTS VALIDATION_STATUS VARCHAR(16) DEFAULT '' NOT NULL");
      statement.execute("ALTER TABLE DISCOVERY_CANDIDATES ADD COLUMN IF NOT EXISTS VALIDATION_JSON VARCHAR(4000) DEFAULT '' NOT NULL");
      statement.execute("ALTER TABLE DISCOVERY_CANDIDATES ADD COLUMN IF NOT EXISTS VALIDATED_AT VARCHAR(40) DEFAULT '' NOT NULL");
      statement.execute("""
          CREATE TABLE IF NOT EXISTS DISCOVERY_RUNS (
            RUN_ID VARCHAR(80) PRIMARY KEY,
            STARTED_AT VARCHAR(40) NOT NULL,
            FINISHED_AT VARCHAR(40) NOT NULL,
            STATUS VARCHAR(32) NOT NULL,
            DISCOVERED INT NOT NULL,
            INSERTED INT NOT NULL,
            UPDATED INT NOT NULL,
            AUTO_PROMOTED INT DEFAULT 0 NOT NULL,
            AUTO_ARCHIVED INT DEFAULT 0 NOT NULL,
            MESSAGE VARCHAR(1000) NOT NULL,
            SOURCE_STATS VARCHAR(4000) DEFAULT '' NOT NULL
          )
          """);
      statement.execute("ALTER TABLE DISCOVERY_RUNS ADD COLUMN IF NOT EXISTS AUTO_PROMOTED INT DEFAULT 0 NOT NULL");
      statement.execute("ALTER TABLE DISCOVERY_RUNS ADD COLUMN IF NOT EXISTS AUTO_ARCHIVED INT DEFAULT 0 NOT NULL");
      statement.execute("ALTER TABLE DISCOVERY_RUNS ADD COLUMN IF NOT EXISTS SOURCE_STATS VARCHAR(4000) DEFAULT '' NOT NULL");
      statement.execute("""
          CREATE TABLE IF NOT EXISTS DISCOVERY_CONFIG (
            ID INT PRIMARY KEY,
            CONFIG_JSON VARCHAR(8000) NOT NULL,
            UPDATED_AT VARCHAR(40) NOT NULL,
            UPDATED_BY VARCHAR(120) NOT NULL
          )
          """);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
    loadAndApplyConfigOverrides();
  }

  @PreDestroy
  public void shutdown() {
    discoveryExecutor.shutdownNow();
  }

  @Scheduled(cron = "${vasp.intake.discovery.cron:0 15 3 ? * MON}")
  public void weeklyDiscovery() {
    if (!properties.getDiscovery().isEnabled()) {
      return;
    }
    if (!running.compareAndSet(false, true)) {
      return; // A discovery run is already in progress.
    }
    try {
      runDiscoveryInternal("system");
    } catch (Exception ignored) {
      // Scheduled discovery must not break the web application.
    } finally {
      running.set(false);
    }
  }

  public List<DiscoverySourceResponse> listSources() {
    return List.of(
        source("datacite", "DataCite", "https://api.datacite.org/", "已接入", "每周一 03:15", "跨 Zenodo、Figshare、Materials Cloud 等 DOI 元数据检索"),
        source("zenodo", "Zenodo", "https://zenodo.org/", "已接入（直接 API）", "随发现任务", "数据集记录：DOI、许可证、文件下载链接、大小与格式"),
        source("figshare", "Figshare", "https://figshare.com/", "已接入（直接 API）", "随发现任务", "数据集检索：DOI、许可证、文件下载链接、大小、标签与分类"),
        source("materials-cloud", "Materials Cloud", "https://www.materialscloud.org/", "经 DataCite 间接发现", "随 DataCite", "DFT 工作流、晶体结构、AiiDA 归档"),
        source("nomad", "NOMAD", "https://nomad-lab.eu/", "已接入（datasets API）", "随发现任务", "NOMAD 公开数据集：名称、DOI 与归档入口；需按 dataset_id 拉取归档解析"),
        source("dryad", "Dryad", "https://datadryad.org/", "已接入（直接 API）", "随发现任务", "开放数据仓库：DOI、CC0 许可、数据包下载入口；跨学科，按相关度筛选"),
        source("openaire", "OpenAIRE", "https://www.openaire.eu/", "已接入（datasets API）", "随发现任务", "欧洲开放科学聚合：跨仓库数据集 DOI 与元数据；广域来源，按相关度筛选"),
        source("materials-project", "Materials Project", "https://materialsproject.org/", "连接器待开发", "手动触发后记录", "需 API Key 与材料 ID 映射"),
        source("aflow", "AFLOW", "https://aflow.org/", "连接器待开发", "手动触发后记录", "无机晶体 DFT 属性与结构"),
        source("oqmd", "OQMD", "https://oqmd.org/", "连接器待开发", "手动触发后记录", "晶体结构、形成能、稳定性数据")
    );
  }

  public DiscoveryConfigResponse getConfig(String authorization) {
    authService.requireQualityReviewAccess(authorization);
    IntakeProperties.Discovery d = properties.getDiscovery();
    return new DiscoveryConfigResponse(
        d.isEnabled(),
        d.getCron(),
        d.isDatacite(),
        d.isZenodo(),
        d.isNomad(),
        d.isFigshare(),
        d.isDryad(),
        d.isOpenaire(),
        d.getMaxResultsPerQuery(),
        d.getContactEmail(),
        d.getQueries(),
        d.getValidate().isEnabled(),
        d.getAutoPromote().isEnabled(),
        d.getAutoPromote().getMinScore(),
        d.getAutoPromote().getMinRelevance(),
        d.getAutoPromote().isRequireLicense(),
        d.getAutoPromote().isRequireValidationPass(),
        d.getAutoPromote().getMaxPerRun(),
        d.getAutoArchive().isEnabled(),
        d.getAutoArchive().getMaxScore(),
        d.getAutoAdapt().isEnabled(),
        d.getAutoAdapt().getMaxDownloadMb(),
        d.getAutoAdapt().getSampleMb()
    );
  }

  /** Super-admin: apply editable config overrides at runtime and persist them. */
  public DiscoveryConfigResponse updateConfig(String authorization, DiscoveryConfigUpdateRequest request) {
    authService.requireSuperAdmin(authorization);
    String operator = authService.me(authorization).username();
    if (request != null) {
      applyConfigOverrides(request);
    }
    persistConfig(operator);
    return getConfig(authorization);
  }

  private void applyConfigOverrides(DiscoveryConfigUpdateRequest r) {
    IntakeProperties.Discovery d = properties.getDiscovery();
    if (r.enabled() != null) d.setEnabled(r.enabled());
    if (r.queries() != null) d.setQueries(sanitizeQueries(r.queries()));
    if (r.maxResultsPerQuery() != null) d.setMaxResultsPerQuery(clamp(r.maxResultsPerQuery(), 1, 50));
    if (r.datacite() != null) d.setDatacite(r.datacite());
    if (r.zenodo() != null) d.setZenodo(r.zenodo());
    if (r.figshare() != null) d.setFigshare(r.figshare());
    if (r.nomad() != null) d.setNomad(r.nomad());
    if (r.dryad() != null) d.setDryad(r.dryad());
    if (r.openaire() != null) d.setOpenaire(r.openaire());
    if (r.validateEnabled() != null) d.getValidate().setEnabled(r.validateEnabled());
    IntakeProperties.AutoPromote ap = d.getAutoPromote();
    if (r.autoPromoteEnabled() != null) ap.setEnabled(r.autoPromoteEnabled());
    if (r.autoPromoteMinScore() != null) ap.setMinScore(clamp(r.autoPromoteMinScore(), 0, 100));
    if (r.autoPromoteMinRelevance() != null) ap.setMinRelevance(clamp(r.autoPromoteMinRelevance(), 0, 100));
    if (r.autoPromoteRequireLicense() != null) ap.setRequireLicense(r.autoPromoteRequireLicense());
    if (r.autoPromoteRequireValidationPass() != null) ap.setRequireValidationPass(r.autoPromoteRequireValidationPass());
    if (r.autoPromoteMaxPerRun() != null) ap.setMaxPerRun(clamp(r.autoPromoteMaxPerRun(), 1, 100));
    IntakeProperties.AutoArchive aa = d.getAutoArchive();
    if (r.autoArchiveEnabled() != null) aa.setEnabled(r.autoArchiveEnabled());
    if (r.autoArchiveMaxScore() != null) aa.setMaxScore(clamp(r.autoArchiveMaxScore(), 0, 100));
    IntakeProperties.AutoAdapt ad = d.getAutoAdapt();
    if (r.autoAdaptEnabled() != null) ad.setEnabled(r.autoAdaptEnabled());
    if (r.autoAdaptMaxDownloadMb() != null) ad.setMaxDownloadMb(clamp(r.autoAdaptMaxDownloadMb(), 1, 4096));
    if (r.autoAdaptSampleMb() != null) ad.setSampleMb(clamp(r.autoAdaptSampleMb(), 1, 256));
  }

  private DiscoveryConfigUpdateRequest snapshotConfig() {
    IntakeProperties.Discovery d = properties.getDiscovery();
    IntakeProperties.AutoPromote ap = d.getAutoPromote();
    IntakeProperties.AutoArchive aa = d.getAutoArchive();
    IntakeProperties.AutoAdapt ad = d.getAutoAdapt();
    return new DiscoveryConfigUpdateRequest(
        d.isEnabled(), new ArrayList<>(d.getQueries()), d.getMaxResultsPerQuery(),
        d.isDatacite(), d.isZenodo(), d.isFigshare(), d.isNomad(), d.isDryad(), d.isOpenaire(),
        d.getValidate().isEnabled(),
        ap.isEnabled(), ap.getMinScore(), ap.getMinRelevance(), ap.isRequireLicense(),
        ap.isRequireValidationPass(), ap.getMaxPerRun(),
        aa.isEnabled(), aa.getMaxScore(),
        ad.isEnabled(), ad.getMaxDownloadMb(), ad.getSampleMb());
  }

  private void persistConfig(String operator) {
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             MERGE INTO DISCOVERY_CONFIG (ID, CONFIG_JSON, UPDATED_AT, UPDATED_BY)
             KEY (ID) VALUES (1, ?, ?, ?)
             """)) {
      statement.setString(1, objectMapper.writeValueAsString(snapshotConfig()));
      statement.setString(2, Instant.now().toString());
      statement.setString(3, limit(operator, 120));
      statement.executeUpdate();
    } catch (Exception ex) {
      throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR, "保存发现配置失败: " + ex.getMessage());
    }
  }

  private void loadAndApplyConfigOverrides() {
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(
             "SELECT CONFIG_JSON FROM DISCOVERY_CONFIG WHERE ID = 1");
         ResultSet rs = statement.executeQuery()) {
      if (rs.next()) {
        String json = rs.getString("CONFIG_JSON");
        if (json != null && !json.isBlank()) {
          applyConfigOverrides(objectMapper.readValue(json, DiscoveryConfigUpdateRequest.class));
        }
      }
    } catch (Exception ignored) {
      // Persisted overrides are best-effort; fall back to yml defaults on any error.
    }
  }

  private static int clamp(int value, int min, int max) {
    return Math.max(min, Math.min(max, value));
  }

  private static List<String> sanitizeQueries(List<String> queries) {
    List<String> cleaned = new ArrayList<>();
    for (String query : queries) {
      if (query == null) {
        continue;
      }
      String trimmed = query.trim();
      if (!trimmed.isBlank() && trimmed.length() <= 200) {
        cleaned.add(trimmed);
        if (cleaned.size() >= 20) {
          break;
        }
      }
    }
    return cleaned.isEmpty()
        ? new ArrayList<>(List.of("computational materials dataset DFT energy force"))
        : cleaned;
  }

  public List<DiscoveryRunResponse> listRuns(String authorization) {
    authService.requireQualityReviewAccess(authorization);
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(
             "SELECT * FROM DISCOVERY_RUNS ORDER BY STARTED_AT DESC LIMIT 20");
         ResultSet rs = statement.executeQuery()) {
      List<DiscoveryRunResponse> rows = new ArrayList<>();
      while (rs.next()) {
        rows.add(runFrom(rs));
      }
      return rows;
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public DiscoveryRunResponse runDiscovery(String authorization) {
    authService.requireDatasetReviewAccess(authorization);
    String operator = authService.me(authorization).username();
    if (!running.compareAndSet(false, true)) {
      return new DiscoveryRunResponse(
          "discover-in-progress",
          Instant.now().toString(),
          "",
          "RUNNING",
          0, 0, 0, 0, 0,
          "已有自动发现任务正在执行，请稍后查看运行记录与候选列表。",
          List.of()
      );
    }
    String runId = "discover-" + UUID.randomUUID();
    String startedAt = Instant.now().toString();
    DiscoveryRunResponse runningResponse = new DiscoveryRunResponse(
        runId,
        startedAt,
        "",
        "RUNNING",
        0, 0, 0, 0, 0,
        "自动发现任务已启动，后台正在检索多源（DataCite / Zenodo / NOMAD）并自动分诊候选。",
        List.of()
    );
    saveRun(runningResponse, operator);
    discoveryExecutor.submit(() -> {
      try {
        runDiscoveryInternal(operator, runId, startedAt);
      } finally {
        running.set(false);
      }
    });
    return runningResponse;
  }

  public List<DiscoveryCandidateResponse> listCandidates(String authorization) {
    authService.requireQualityReviewAccess(authorization);
    String sql = "SELECT * FROM DISCOVERY_CANDIDATES ORDER BY SCORE DESC, UPDATED_AT DESC LIMIT 200";
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(sql);
         ResultSet rs = statement.executeQuery()) {
      List<DiscoveryCandidateResponse> rows = new ArrayList<>();
      while (rs.next()) {
        rows.add(candidateFrom(rs));
      }
      return rows;
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public DiscoveryCandidateResponse reviewCandidate(
      String authorization,
      long id,
      DiscoveryDecisionRequest request
  ) {
    authService.requireDatasetReviewAccess(authorization);
    String decision = normalizeDecision(request == null ? null : request.decision());
    String note = optional(request == null ? null : request.note(), 1000);
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DISCOVERY_CANDIDATES
             SET STATUS = ?, REVIEW_NOTE = ?, UPDATED_AT = ?
             WHERE ID = ?
             """)) {
      statement.setString(1, decision);
      statement.setString(2, note);
      statement.setString(3, now);
      statement.setLong(4, id);
      if (statement.executeUpdate() == 0) {
        throw new ApiException(HttpStatus.NOT_FOUND, "找不到自动发现候选: " + id);
      }
      return findCandidate(id);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  public DatasetSubmissionResponse promoteCandidate(String authorization, long id) {
    authService.requireDatasetReviewAccess(authorization);
    DiscoveryCandidateResponse candidate = findCandidate(id);
    DatasetSubmissionResponse submission = intakeService.submitAsSystem(
        "auto-discovery",
        new DatasetSubmissionRequest(
            candidate.title(),
            inferDataType(candidate),
            candidate.recommendation(),
            candidate.paperUrl(),
            candidate.dataUrl(),
            candidate.dataFormat(),
            candidate.license(),
            candidate.detectedFields()
        )
    );
    reviewCandidate(authorization, id, new DiscoveryDecisionRequest("APPROVED", "已转入数据接入审核队列 #" + submission.id()));
    return submission;
  }

  /** Re-run automated proof-reading for one candidate and persist the fresh report. */
  public DiscoveryCandidateResponse validateCandidate(String authorization, long id) {
    authService.requireDatasetReviewAccess(authorization);
    DiscoveryCandidateResponse candidate = findCandidate(id);
    ValidationReport report = validationService.validate(candidate);
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DISCOVERY_CANDIDATES
             SET VALIDATION_STATUS = ?, VALIDATION_JSON = ?, VALIDATED_AT = ?, UPDATED_AT = ?
             WHERE ID = ?
             """)) {
      statement.setString(1, report.status());
      statement.setString(2, serializeReport(report));
      statement.setString(3, report.validatedAt());
      statement.setString(4, now);
      statement.setLong(5, id);
      if (statement.executeUpdate() == 0) {
        throw new ApiException(HttpStatus.NOT_FOUND, "找不到自动发现候选: " + id);
      }
      return findCandidate(id);
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  /**
   * Auto-triage after every discovery run: high-confidence candidates are pushed
   * into the human review queue, obvious low-signal ones are archived. Publishing
   * still requires manual super-admin approval downstream.
   */
  private TriageResult triageCandidates(String operator) {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    int promoted = 0;
    int archived = 0;
    if (cfg.getAutoPromote().isEnabled()) {
      promoted = autoPromoteHighConfidence(operator, cfg.getAutoPromote());
    }
    if (cfg.getAutoArchive().isEnabled()) {
      archived = autoArchiveLowSignal(cfg.getAutoArchive());
    }
    return new TriageResult(promoted, archived);
  }

  private int autoPromoteHighConfidence(String operator, IntakeProperties.AutoPromote cfg) {
    List<DiscoveryCandidateResponse> ready = new ArrayList<>();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(
             "SELECT * FROM DISCOVERY_CANDIDATES WHERE STATUS = 'CANDIDATE' AND SCORE >= ? ORDER BY SCORE DESC, UPDATED_AT DESC")) {
      statement.setInt(1, cfg.getMinScore());
      try (ResultSet rs = statement.executeQuery()) {
        int cap = Math.max(1, cfg.getMaxPerRun());
        while (rs.next() && ready.size() < cap) {
          DiscoveryCandidateResponse candidate = candidateFrom(rs);
          if (candidate.doi().isBlank() || candidate.dataUrl().isBlank()) {
            continue;
          }
          if (candidate.relevance() < cfg.getMinRelevance()) {
            continue; // On-topic gate: completeness alone must not auto-promote off-topic data.
          }
          if ("FAIL".equals(candidate.validationStatus())) {
            continue; // Proof-reading flagged it (dead link / off-topic / duplicate); never auto-promote.
          }
          if (cfg.isRequireValidationPass() && !"PASS".equals(candidate.validationStatus())) {
            continue; // Strict mode: only fully-passing candidates auto-promote.
          }
          if (cfg.isRequireLicense() && !hasUsableLicense(candidate.license())) {
            continue;
          }
          ready.add(candidate);
        }
      }
    } catch (SQLException ex) {
      throw databaseError(ex);
    }

    int promoted = 0;
    for (DiscoveryCandidateResponse candidate : ready) {
      try {
        DatasetSubmissionResponse submission = intakeService.submitAsSystem(
            "auto-discovery",
            new DatasetSubmissionRequest(
                candidate.title(),
                inferDataType(candidate),
                candidate.recommendation(),
                candidate.paperUrl(),
                candidate.dataUrl(),
                candidate.dataFormat(),
                candidate.license(),
                candidate.detectedFields()
            )
        );
        updateCandidateStatus(
            candidate.id(),
            "APPROVED",
            "自动分诊：评分 " + candidate.score() + " 达标，已自动转入接入审核队列 #" + submission.id()
                + "（操作人 " + operator + "），等待人工核验来源与许可证。");
        promoted++;
        if (properties.getDiscovery().getAutoAdapt().isEnabled()) {
          try {
            intakeService.profileSubmissionAsSystem(submission.id());
          } catch (RuntimeException ignored) {
            // Auto-adapter is best-effort; the promotion already succeeded.
          }
        }
      } catch (RuntimeException ex) {
        // A single malformed candidate must not abort the whole batch; it stays
        // CANDIDATE so a human can still review it.
      }
    }
    return promoted;
  }

  private int autoArchiveLowSignal(IntakeProperties.AutoArchive cfg) {
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DISCOVERY_CANDIDATES
             SET STATUS = 'ARCHIVED', REVIEW_NOTE = ?, UPDATED_AT = ?
             WHERE STATUS = 'CANDIDATE' AND SCORE <= ?
             """)) {
      statement.setString(1, "自动分诊：评分不足 " + cfg.getMaxScore() + "，已自动归档为线索，可人工恢复。");
      statement.setString(2, now);
      statement.setInt(3, cfg.getMaxScore());
      return statement.executeUpdate();
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  private void updateCandidateStatus(long id, String status, String note) {
    String now = Instant.now().toString();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             UPDATE DISCOVERY_CANDIDATES
             SET STATUS = ?, REVIEW_NOTE = ?, UPDATED_AT = ?
             WHERE ID = ?
             """)) {
      statement.setString(1, status);
      statement.setString(2, limit(note, 1000));
      statement.setString(3, now);
      statement.setLong(4, id);
      statement.executeUpdate();
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  private static boolean hasUsableLicense(String license) {
    if (license == null) {
      return false;
    }
    String value = license.trim().toLowerCase(Locale.ROOT);
    return !value.isBlank()
        && !value.equals("待确认")
        && !value.equals("未说明")
        && !value.equals("待管理员确认");
  }

  private String userAgent() {
    String contact = properties.getDiscovery().getContactEmail();
    return contact == null || contact.isBlank()
        ? "VASP-Show-auto-discovery"
        : "VASP-Show-auto-discovery (mailto:" + contact.trim() + ")";
  }

  private DiscoveryRunResponse runDiscoveryInternal(String operator) {
    return runDiscoveryInternal(operator, "discover-" + UUID.randomUUID(), Instant.now().toString());
  }

  private DiscoveryRunResponse runDiscoveryInternal(String operator, String runId, String startedAt) {
    int discovered = 0;
    int inserted = 0;
    int updated = 0;
    int autoPromoted = 0;
    int autoArchived = 0;
    String status = "SUCCESS";
    String message = "自动发现完成。";
    List<DiscoverySourceStat> sourceStats = new ArrayList<>();
    try {
      DiscoverAllResult discovery = discoverAll();
      sourceStats = discovery.stats();
      List<CandidateDraft> drafts = discovery.drafts();
      discovered = drafts.size();
      boolean validateEnabled = properties.getDiscovery().getValidate().isEnabled();
      for (CandidateDraft draft : drafts) {
        ValidationReport report = validateEnabled ? validationService.validate(toCandidate(draft)) : null;
        UpsertResult result = upsertCandidate(draft, report);
        if (result.inserted()) {
          inserted++;
        } else if (result.updated()) {
          updated++;
        }
      }
      TriageResult triage = triageCandidates(operator);
      autoPromoted = triage.promoted();
      autoArchived = triage.archived();
      boolean allFailed = !sourceStats.isEmpty() && sourceStats.stream().allMatch(s -> "ERROR".equals(s.status()));
      if (allFailed) {
        status = "FAILED";
        message = "自动发现失败：所有数据源均未成功返回（" + summarizeFailures(sourceStats) + "）。";
      } else if (drafts.isEmpty() && autoPromoted == 0 && autoArchived == 0) {
        status = sourceStats.stream().anyMatch(s -> "ERROR".equals(s.status())) ? "PARTIAL" : "SUCCESS";
        message = "未发现新候选；请稍后重试或调整关键词。" + sourceSuffix(sourceStats);
      } else {
        status = sourceStats.stream().anyMatch(s -> "ERROR".equals(s.status())) ? "PARTIAL" : "SUCCESS";
        message = String.format(
            "自动发现完成：发现 %d，新增 %d，更新 %d，自动转入 %d，自动归档 %d。%s",
            discovered, inserted, updated, autoPromoted, autoArchived, sourceSuffix(sourceStats));
      }
    } catch (Exception ex) {
      status = "FAILED";
      message = "自动发现失败: " + ex.getMessage();
    }
    String finishedAt = Instant.now().toString();
    DiscoveryRunResponse run = new DiscoveryRunResponse(
        runId, startedAt, finishedAt, status, discovered, inserted, updated,
        autoPromoted, autoArchived, message, sourceStats);
    saveRun(run, operator);
    return run;
  }

  private DiscoverAllResult discoverAll() {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    record SourceJob(String name, boolean enabled, DraftSupplier supplier) {
    }
    List<SourceJob> jobs = List.of(
        new SourceJob("DataCite", cfg.isDatacite(), this::discoverFromDataCite),
        new SourceJob("Zenodo", cfg.isZenodo(), this::discoverFromZenodo),
        new SourceJob("Figshare", cfg.isFigshare(), this::discoverFromFigshare),
        new SourceJob("Dryad", cfg.isDryad(), this::discoverFromDryad),
        new SourceJob("OpenAIRE", cfg.isOpenaire(), this::discoverFromOpenAire),
        new SourceJob("NOMAD", cfg.isNomad(), this::discoverFromNomad));

    // Run every source concurrently so a whole run takes about as long as the slowest
    // source rather than the sum of them all (a few sources sit near their timeouts).
    ExecutorService pool = Executors.newFixedThreadPool(jobs.size(), runnable -> {
      Thread thread = new Thread(runnable, "vasp-discovery-source");
      thread.setDaemon(true);
      return thread;
    });
    List<SourceResult> results = new ArrayList<>();
    try {
      List<Callable<SourceResult>> tasks = new ArrayList<>();
      for (SourceJob job : jobs) {
        tasks.add(() -> runSourceJob(job.name(), job.enabled(), job.supplier()));
      }
      List<Future<SourceResult>> futures = pool.invokeAll(tasks, 150, TimeUnit.SECONDS);
      for (int i = 0; i < futures.size(); i++) {
        try {
          results.add(futures.get(i).get());
        } catch (Exception ex) {
          results.add(new SourceResult(
              new DiscoverySourceStat(jobs.get(i).name(), 0, "ERROR", "超时或中断"), List.of()));
        }
      }
    } catch (InterruptedException ex) {
      Thread.currentThread().interrupt();
    } finally {
      pool.shutdownNow();
    }

    // Merge single-threaded with cross-source dedup, preserving source priority order.
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    List<DiscoverySourceStat> stats = new ArrayList<>();
    for (SourceResult result : results) {
      int added = collect(drafts, seen, result.drafts());
      DiscoverySourceStat stat = result.stat();
      if ("OK".equals(stat.status())) {
        stats.add(new DiscoverySourceStat(stat.source(), stat.found(), "OK",
            "命中 " + stat.found() + "，去重后新增 " + added));
      } else {
        stats.add(stat);
      }
    }
    return new DiscoverAllResult(drafts, stats);
  }

  /**
   * Run a single source connector and capture its outcome (drafts + stat) instead of
   * letting an error vanish silently. A failing source no longer looks like an empty one.
   */
  private SourceResult runSourceJob(String name, boolean enabled, DraftSupplier supplier) {
    if (!enabled) {
      return new SourceResult(new DiscoverySourceStat(name, 0, "DISABLED", "数据源已关闭"), List.of());
    }
    try {
      List<CandidateDraft> found = supplier.get();
      String status = found.isEmpty() ? "EMPTY" : "OK";
      String detail = found.isEmpty() ? "本轮无返回" : "命中 " + found.size();
      return new SourceResult(new DiscoverySourceStat(name, found.size(), status, detail), found);
    } catch (Exception ex) {
      String reason = ex.getMessage() == null ? ex.getClass().getSimpleName() : ex.getMessage();
      return new SourceResult(new DiscoverySourceStat(name, 0, "ERROR", limit(reason, 200)), List.of());
    }
  }

  private static int collect(List<CandidateDraft> target, Set<String> seen, List<CandidateDraft> incoming) {
    int added = 0;
    for (CandidateDraft draft : incoming) {
      if (seen.add(draft.uniqueKey())) {
        target.add(draft);
        added++;
      }
    }
    return added;
  }

  private static String sourceSuffix(List<DiscoverySourceStat> stats) {
    if (stats == null || stats.isEmpty()) {
      return "";
    }
    List<String> parts = new ArrayList<>();
    for (DiscoverySourceStat stat : stats) {
      parts.add(stat.source() + ":" + stat.status() + "(" + stat.found() + ")");
    }
    return "来源 " + String.join(" ", parts) + "。";
  }

  private static String summarizeFailures(List<DiscoverySourceStat> stats) {
    List<String> parts = new ArrayList<>();
    for (DiscoverySourceStat stat : stats) {
      if ("ERROR".equals(stat.status())) {
        parts.add(stat.source() + ": " + stat.detail());
      }
    }
    return String.join("; ", parts);
  }

  private List<CandidateDraft> discoverFromZenodo() throws Exception {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    List<String> queries = cfg.getQueries() == null || cfg.getQueries().isEmpty()
        ? List.of("computational materials dataset DFT energy force")
        : cfg.getQueries();
    int pageSize = Math.max(1, Math.min(cfg.getMaxResultsPerQuery(), 50));
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    for (String query : queries) {
      if (query == null || query.isBlank()) {
        continue;
      }
      String url = "https://zenodo.org/api/records?type=dataset&sort=mostrecent&size=" + pageSize
          + "&q=" + URLEncoder.encode(query, StandardCharsets.UTF_8);
      HttpRequest request = HttpRequest.newBuilder(URI.create(url))
          .GET()
          .timeout(Duration.ofSeconds(16))
          .header("User-Agent", userAgent())
          .header("Accept", "application/json")
          .build();
      HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      if (response.statusCode() < 200 || response.statusCode() >= 300) {
        continue;
      }
      JsonNode hits = objectMapper.readTree(response.body()).path("hits").path("hits");
      if (!hits.isArray()) {
        continue;
      }
      for (JsonNode item : hits) {
        CandidateDraft draft = draftFromZenodo(item);
        if (draft == null || !seen.add(draft.uniqueKey())) {
          continue;
        }
        drafts.add(draft);
      }
    }
    return drafts;
  }

  private CandidateDraft draftFromZenodo(JsonNode item) {
    String doi = text(item, "doi");
    JsonNode metadata = item.path("metadata");
    String title = text(metadata, "title");
    if (title.isBlank() && doi.isBlank()) {
      return null;
    }
    String description = stripHtml(text(metadata, "description"));
    String license = zenodoLicense(metadata.path("license"));
    JsonNode links = item.path("links");
    String landing = firstNonBlank(
        text(links, "self_html"),
        text(links, "html"),
        links.path("doi").asText(""));

    String fileName = "";
    String dataUrl = "";
    String scale = "待下载清点";
    JsonNode files = item.path("files");
    if (files.isArray() && !files.isEmpty()) {
      JsonNode file = files.get(0);
      fileName = firstNonBlank(text(file, "key"), text(file, "filename"));
      dataUrl = firstNonBlank(
          file.path("links").path("self").asText(""),
          file.path("links").path("download").asText(""));
      long size = file.path("size").asLong(file.path("filesize").asLong(0L));
      if (size > 0) {
        scale = size + " bytes";
      }
    }
    if (dataUrl.isBlank()) {
      dataUrl = landing;
    }
    String paperUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    String combined = (title + " " + description + " " + fileName + " " + dataUrl).toLowerCase(Locale.ROOT);
    String format = detectFormat(fileName, "");
    String fields = detectFields(combined);
    String method = inferMethod(combined);
    PreflightProbe probe = new PreflightProbe(format, scale, fields, parserPlan(format, combined));
    int relevance = relevanceOf(combined, probe.format(), probe.fields(), method);
    int score = scoreCandidate(doi, dataUrl, license, probe, relevance);
    String recommendation = recommendation(title, doi, dataUrl, license, probe, relevance, score);
    // Prefer Zenodo's concept DOI so different versions of one dataset collapse to a single candidate.
    String conceptDoi = text(item, "conceptdoi");
    String uniqueKey = normalizeKey(!conceptDoi.isBlank() ? conceptDoi : (!doi.isBlank() ? doi : dataUrl));
    return new CandidateDraft(
        "Zenodo",
        title,
        doi,
        paperUrl,
        dataUrl,
        "Zenodo",
        license.isBlank() ? "待确认" : license,
        probe.format(),
        probe.scale(),
        method,
        probe.fields(),
        probe.parserPlan(),
        score,
        relevance,
        recommendation,
        uniqueKey
    );
  }

  private List<CandidateDraft> discoverFromFigshare() throws Exception {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    List<String> queries = cfg.getQueries() == null || cfg.getQueries().isEmpty()
        ? List.of("computational materials dataset DFT energy force")
        : cfg.getQueries();
    int pageSize = Math.max(1, Math.min(cfg.getMaxResultsPerQuery(), 25));
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    int lastErrorStatus = 0;
    String lastErrorDetail = "";
    for (String query : queries) {
      if (query == null || query.isBlank()) {
        continue;
      }
      ObjectNode payload = objectMapper.createObjectNode();
      payload.put("search_for", query);
      payload.put("page_size", pageSize);
      payload.put("item_type", 3); // 3 = dataset
      payload.put("order", "published_date");
      payload.put("order_direction", "desc");
      HttpRequest request = HttpRequest.newBuilder(URI.create("https://api.figshare.com/v2/articles/search"))
          .POST(HttpRequest.BodyPublishers.ofString(objectMapper.writeValueAsString(payload), StandardCharsets.UTF_8))
          .timeout(Duration.ofSeconds(16))
          .header("User-Agent", userAgent())
          .header("Content-Type", "application/json")
          .header("Accept", "application/json")
          .build();
      HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      if (response.statusCode() < 200 || response.statusCode() >= 300) {
        lastErrorStatus = response.statusCode();
        lastErrorDetail = limit(response.body(), 160);
        continue;
      }
      JsonNode list = objectMapper.readTree(response.body());
      if (!list.isArray()) {
        lastErrorStatus = -1;
        lastErrorDetail = "响应非数组";
        continue;
      }
      for (JsonNode summary : list) {
        long id = summary.path("id").asLong(0L);
        if (id <= 0) {
          continue;
        }
        CandidateDraft draft = draftFromFigshare(fetchFigshareDetail(id), summary);
        if (draft == null || !seen.add(draft.uniqueKey())) {
          continue;
        }
        drafts.add(draft);
      }
    }
    if (drafts.isEmpty() && lastErrorStatus != 0) {
      throw new IllegalStateException("Figshare HTTP " + lastErrorStatus
          + (lastErrorDetail.isBlank() ? "" : " · " + lastErrorDetail));
    }
    return drafts;
  }

  private JsonNode fetchFigshareDetail(long id) {
    try {
      HttpRequest request = HttpRequest.newBuilder(URI.create("https://api.figshare.com/v2/articles/" + id))
          .GET()
          .timeout(Duration.ofSeconds(12))
          .header("User-Agent", userAgent())
          .header("Accept", "application/json")
          .build();
      HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      if (response.statusCode() < 200 || response.statusCode() >= 300) {
        return null;
      }
      return objectMapper.readTree(response.body());
    } catch (Exception ex) {
      return null; // Detail is best-effort; fall back to the search summary.
    }
  }

  private CandidateDraft draftFromFigshare(JsonNode detail, JsonNode summary) {
    String title = firstNonBlank(text(detail, "title"), text(summary, "title"));
    String doi = firstNonBlank(text(detail, "doi"), text(summary, "doi"));
    String landing = firstNonBlank(
        text(detail, "url_public_html"), text(summary, "url_public_html"), text(summary, "url"));
    if (title.isBlank() && doi.isBlank()) {
      return null;
    }
    String description = stripHtml(text(detail, "description"));
    JsonNode licenseNode = detail == null ? null : detail.path("license");
    String license = licenseNode == null ? "" : firstNonBlank(text(licenseNode, "name"), text(licenseNode, "value"));

    String fileName = "";
    String dataUrl = "";
    String scale = "待下载清点";
    JsonNode files = detail == null ? null : detail.path("files");
    if (files != null && files.isArray() && !files.isEmpty()) {
      JsonNode file = files.get(0);
      fileName = text(file, "name");
      dataUrl = firstNonBlank(text(file, "download_url"));
      long size = file.path("size").asLong(0L);
      if (size > 0) {
        scale = size + " bytes";
      }
    }
    if (dataUrl.isBlank()) {
      dataUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    }
    String paperUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    String tags = joinFigshareTags(detail);
    String combined = (title + " " + description + " " + fileName + " " + tags + " " + dataUrl).toLowerCase(Locale.ROOT);
    String format = detectFormat(fileName, "");
    String fields = detectFields(combined);
    String method = inferMethod(combined);
    PreflightProbe probe = new PreflightProbe(format, scale, fields, parserPlan(format, combined));
    int relevance = relevanceOf(combined, probe.format(), probe.fields(), method);
    int score = scoreCandidate(doi, dataUrl, license, probe, relevance);
    String recommendation = recommendation(title, doi, dataUrl, license, probe, relevance, score);
    String uniqueKey = normalizeKey(!doi.isBlank() ? doi : (!dataUrl.isBlank() ? dataUrl : landing));
    return new CandidateDraft(
        "Figshare",
        title,
        doi,
        paperUrl,
        dataUrl,
        "Figshare",
        license.isBlank() ? "待确认" : license,
        probe.format(),
        probe.scale(),
        method,
        probe.fields(),
        probe.parserPlan(),
        score,
        relevance,
        recommendation,
        uniqueKey
    );
  }

  private static String joinFigshareTags(JsonNode detail) {
    if (detail == null) {
      return "";
    }
    List<String> values = new ArrayList<>();
    JsonNode tags = detail.path("tags");
    if (tags.isArray()) {
      for (JsonNode tag : tags) {
        String value = tag.asText("").trim();
        if (!value.isBlank()) {
          values.add(value);
        }
      }
    }
    JsonNode categories = detail.path("categories");
    if (categories.isArray()) {
      for (JsonNode category : categories) {
        String value = category.path("title").asText("").trim();
        if (!value.isBlank()) {
          values.add(value);
        }
      }
    }
    return String.join(" ", values);
  }

  private List<CandidateDraft> discoverFromDryad() throws Exception {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    List<String> queries = cfg.getQueries() == null || cfg.getQueries().isEmpty()
        ? List.of("computational materials dataset DFT energy force")
        : cfg.getQueries();
    int perPage = Math.max(1, Math.min(cfg.getMaxResultsPerQuery(), 25));
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    for (String query : queries) {
      if (query == null || query.isBlank()) {
        continue;
      }
      String url = "https://datadryad.org/api/v2/search?per_page=" + perPage
          + "&q=" + URLEncoder.encode(query, StandardCharsets.UTF_8);
      HttpRequest request = HttpRequest.newBuilder(URI.create(url))
          .GET()
          .timeout(Duration.ofSeconds(16))
          .header("User-Agent", userAgent())
          .header("Accept", "application/json")
          .build();
      HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      if (response.statusCode() < 200 || response.statusCode() >= 300) {
        continue;
      }
      JsonNode datasets = objectMapper.readTree(response.body()).path("_embedded").path("stash:datasets");
      if (!datasets.isArray()) {
        continue;
      }
      for (JsonNode item : datasets) {
        CandidateDraft draft = draftFromDryad(item);
        if (draft == null || !seen.add(draft.uniqueKey())) {
          continue;
        }
        drafts.add(draft);
      }
    }
    return drafts;
  }

  private CandidateDraft draftFromDryad(JsonNode item) {
    String identifier = text(item, "identifier");
    String doi = identifier.toLowerCase(Locale.ROOT).startsWith("doi:") ? identifier.substring(4) : identifier;
    String title = text(item, "title");
    if (title.isBlank() && doi.isBlank()) {
      return null;
    }
    String description = stripHtml(text(item, "abstract"));
    String license = text(item, "license");
    String downloadPath = item.path("_links").path("stash:download").path("href").asText("");
    String landingPath = firstNonBlank(
        item.path("_links").path("stash:dataset").path("href").asText(""),
        item.path("_links").path("self").path("href").asText(""));
    String dataUrl = downloadPath.isBlank() ? "" : "https://datadryad.org" + downloadPath;
    String landing = landingPath.isBlank()
        ? (doi.isBlank() ? "" : "https://doi.org/" + doi)
        : "https://datadryad.org" + landingPath;
    if (dataUrl.isBlank()) {
      dataUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    }
    String paperUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    String combined = (title + " " + description).toLowerCase(Locale.ROOT);
    String format = detectFormat(combined, "");
    if ("待识别".equals(format)) {
      format = "压缩包"; // Dryad serves dataset bundles (zip)
    }
    String fields = detectFields(combined);
    String method = inferMethod(combined);
    PreflightProbe probe = new PreflightProbe(format, "待下载清点", fields, parserPlan(format, combined));
    int relevance = relevanceOf(combined, probe.format(), probe.fields(), method);
    int score = scoreCandidate(doi, dataUrl, license, probe, relevance);
    String recommendation = recommendation(title, doi, dataUrl, license, probe, relevance, score);
    String uniqueKey = normalizeKey(!doi.isBlank() ? doi : dataUrl);
    return new CandidateDraft(
        "Dryad",
        title,
        doi,
        paperUrl,
        dataUrl,
        "Dryad",
        license.isBlank() ? "待确认" : license,
        probe.format(),
        probe.scale(),
        method,
        probe.fields(),
        probe.parserPlan(),
        score,
        relevance,
        recommendation,
        uniqueKey
    );
  }

  private List<CandidateDraft> discoverFromOpenAire() throws Exception {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    List<String> queries = cfg.getQueries() == null || cfg.getQueries().isEmpty()
        ? List.of("computational materials dataset DFT energy force")
        : cfg.getQueries();
    int size = Math.max(1, Math.min(cfg.getMaxResultsPerQuery(), 25));
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    for (String query : queries) {
      if (query == null || query.isBlank()) {
        continue;
      }
      String url = "https://api.openaire.eu/search/datasets?format=json&size=" + size
          + "&keywords=" + URLEncoder.encode(query, StandardCharsets.UTF_8);
      HttpRequest request = HttpRequest.newBuilder(URI.create(url))
          .GET()
          .timeout(Duration.ofSeconds(16))
          .header("User-Agent", userAgent())
          .header("Accept", "application/json")
          .build();
      HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      if (response.statusCode() < 200 || response.statusCode() >= 300) {
        continue;
      }
      JsonNode results = objectMapper.readTree(response.body()).path("response").path("results").path("result");
      for (JsonNode result : asNodeList(results)) {
        CandidateDraft draft = draftFromOpenAire(result);
        if (draft == null || !seen.add(draft.uniqueKey())) {
          continue;
        }
        drafts.add(draft);
      }
    }
    return drafts;
  }

  private CandidateDraft draftFromOpenAire(JsonNode result) {
    JsonNode meta = result.path("metadata").path("oaf:entity").path("oaf:result");
    if (meta.isMissingNode()) {
      meta = result;
    }
    String title = oafText(meta.path("title"));
    String doi = oafDoi(meta.path("pid"));
    String description = stripHtml(oafText(meta.path("description")));
    if (title.isBlank() && doi.isBlank()) {
      return null;
    }
    String landing = !doi.isBlank() ? "https://doi.org/" + doi : "";
    String dataUrl = landing;
    String paperUrl = landing;
    String combined = (title + " " + description).toLowerCase(Locale.ROOT);
    String format = detectFormat(combined, "");
    String fields = detectFields(combined);
    String method = inferMethod(combined);
    PreflightProbe probe = new PreflightProbe(format, "待下载清点", fields, parserPlan(format, combined));
    int relevance = relevanceOf(combined, probe.format(), probe.fields(), method);
    int score = scoreCandidate(doi, dataUrl, "", probe, relevance);
    String recommendation = recommendation(title, doi, dataUrl, "", probe, relevance, score);
    String uniqueKey = !doi.isBlank()
        ? normalizeKey(doi)
        : "openaire:" + limit(title.toLowerCase(Locale.ROOT), 200);
    return new CandidateDraft(
        "OpenAIRE",
        title,
        doi,
        paperUrl,
        dataUrl,
        "OpenAIRE",
        "待确认",
        probe.format(),
        probe.scale(),
        method,
        probe.fields(),
        probe.parserPlan(),
        score,
        relevance,
        recommendation,
        uniqueKey
    );
  }

  /** OpenAIRE nodes are sometimes a single object and sometimes an array. */
  private static List<JsonNode> asNodeList(JsonNode node) {
    if (node == null || node.isMissingNode() || node.isNull()) {
      return List.of();
    }
    if (node.isArray()) {
      List<JsonNode> list = new ArrayList<>();
      node.forEach(list::add);
      return list;
    }
    return List.of(node);
  }

  /** OpenAIRE text is encoded as a raw string, {"$":"..."} or an array of those. */
  private static String oafText(JsonNode node) {
    if (node == null || node.isMissingNode()) {
      return "";
    }
    if (node.isTextual()) {
      return node.asText("").trim();
    }
    if (node.isArray()) {
      for (JsonNode element : node) {
        String value = oafText(element);
        if (!value.isBlank()) {
          return value;
        }
      }
      return "";
    }
    if (node.isObject()) {
      if (node.has("$")) {
        return node.path("$").asText("").trim();
      }
      if (node.has("content")) {
        return node.path("content").asText("").trim();
      }
    }
    return "";
  }

  private static String oafDoi(JsonNode pid) {
    for (JsonNode entry : asNodeList(pid)) {
      if ("doi".equalsIgnoreCase(entry.path("@classid").asText(""))) {
        String value = entry.path("$").asText("").trim();
        if (!value.isBlank()) {
          return value;
        }
      }
    }
    for (JsonNode entry : asNodeList(pid)) {
      String value = oafText(entry);
      if (value.startsWith("10.")) {
        return value;
      }
    }
    return "";
  }

  private List<CandidateDraft> discoverFromNomad() throws Exception {
    int pageSize = Math.max(1, Math.min(properties.getDiscovery().getMaxResultsPerQuery() * 2, 50));
    String url = "https://nomad-lab.eu/prod/v1/api/v1/datasets/?page_size=" + pageSize;
    HttpRequest request = HttpRequest.newBuilder(URI.create(url))
        .GET()
        .timeout(Duration.ofSeconds(16))
        .header("User-Agent", userAgent())
        .header("Accept", "application/json")
        .build();
    HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      return List.of();
    }
    JsonNode data = objectMapper.readTree(response.body()).path("data");
    if (!data.isArray()) {
      return List.of();
    }
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    for (JsonNode item : data) {
      CandidateDraft draft = draftFromNomad(item);
      if (draft == null || !seen.add(draft.uniqueKey())) {
        continue;
      }
      drafts.add(draft);
    }
    return drafts;
  }

  private CandidateDraft draftFromNomad(JsonNode item) {
    String datasetId = text(item, "dataset_id");
    String title = text(item, "dataset_name");
    String doi = text(item, "doi");
    if (title.isBlank() && datasetId.isBlank()) {
      return null;
    }
    String landing = datasetId.isBlank() ? "" : "https://nomad-lab.eu/prod/v1/gui/dataset/id/" + datasetId;
    String dataUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    String paperUrl = !doi.isBlank() ? "https://doi.org/" + doi : landing;
    String datasetType = text(item, "dataset_type");
    String combined = (title + " " + datasetType + " NOMAD archive").toLowerCase(Locale.ROOT);
    String format = "NOMAD archive";
    String fields = detectFields(combined);
    String method = inferMethod(combined);
    PreflightProbe probe = new PreflightProbe(
        format,
        "待 NOMAD API 清点",
        fields,
        "NOMAD 适配器：按 dataset_id 调用 NOMAD entries/archive API 拉取归档，映射 energy/forces/structure 与计算方法、泛函。");
    int relevance = relevanceOf(combined, probe.format(), probe.fields(), method);
    int score = scoreCandidate(doi, dataUrl, "", probe, relevance);
    String recommendation = recommendation(title, doi, dataUrl, "", probe, relevance, score);
    String uniqueKey = !doi.isBlank()
        ? normalizeKey(doi)
        : (datasetId.isBlank() ? normalizeKey(landing) : "nomad:" + datasetId.toLowerCase(Locale.ROOT));
    return new CandidateDraft(
        "NOMAD",
        title,
        doi,
        paperUrl,
        dataUrl,
        "NOMAD",
        "待确认",
        format,
        probe.scale(),
        method,
        probe.fields(),
        probe.parserPlan(),
        score,
        relevance,
        recommendation,
        uniqueKey
    );
  }

  private List<CandidateDraft> discoverFromDataCite() throws Exception {
    IntakeProperties.Discovery cfg = properties.getDiscovery();
    List<String> queries = cfg.getQueries() == null || cfg.getQueries().isEmpty()
        ? List.of("computational materials dataset DFT energy force")
        : cfg.getQueries();
    int pageSize = Math.max(1, Math.min(cfg.getMaxResultsPerQuery(), 50));

    // 1) Fetch all DataCite items (fast sequential GETs), de-duplicating raw items by
    //    DOI/URL so the expensive per-item HEAD probe never runs twice for one dataset.
    List<JsonNode> items = new ArrayList<>();
    Set<String> rawSeen = new LinkedHashSet<>();
    for (String query : queries) {
      if (query == null || query.isBlank()) {
        continue;
      }
      String url = "https://api.datacite.org/dois?query="
          + URLEncoder.encode(query, StandardCharsets.UTF_8)
          + "&page[size]=" + pageSize;
      HttpRequest request = HttpRequest.newBuilder(URI.create(url))
          .GET()
          .timeout(Duration.ofSeconds(16))
          .header("User-Agent", userAgent())
          .build();
      HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
      if (response.statusCode() < 200 || response.statusCode() >= 300) {
        continue;
      }
      JsonNode data = objectMapper.readTree(response.body()).path("data");
      if (!data.isArray()) {
        continue;
      }
      for (JsonNode item : data) {
        JsonNode attributes = item.path("attributes");
        String key = normalizeKey(firstNonBlank(
            text(attributes, "doi"),
            chooseDataUrl(attributes, text(attributes, "url"), text(attributes, "doi"))));
        if (key.isBlank() || rawSeen.add(key)) {
          items.add(item);
        }
      }
    }

    // 2) Probe + build drafts concurrently; reuse stored probes for already-known keys.
    Map<String, String[]> resolved = loadResolvedProbes();
    List<CandidateDraft> built = probeDataCiteConcurrently(items, resolved);

    // 3) Final de-dup by uniqueKey.
    List<CandidateDraft> drafts = new ArrayList<>();
    Set<String> seen = new LinkedHashSet<>();
    for (CandidateDraft draft : built) {
      if (draft != null && seen.add(draft.uniqueKey())) {
        drafts.add(draft);
      }
    }
    return drafts;
  }

  /**
   * Resolve drafts for DataCite items in parallel. The per-item HTTP HEAD/Range probe
   * dominates a discovery run; a small bounded pool turns minutes of sequential probing
   * into seconds while keeping the whole batch time-boxed.
   */
  private List<CandidateDraft> probeDataCiteConcurrently(List<JsonNode> items, Map<String, String[]> resolved) {
    if (items.isEmpty()) {
      return List.of();
    }
    int threads = Math.min(8, items.size());
    ExecutorService pool = Executors.newFixedThreadPool(threads, runnable -> {
      Thread thread = new Thread(runnable, "vasp-datacite-probe");
      thread.setDaemon(true);
      return thread;
    });
    try {
      List<Callable<CandidateDraft>> tasks = new ArrayList<>();
      for (JsonNode item : items) {
        tasks.add(() -> draftFromDataCite(item, resolved));
      }
      List<CandidateDraft> results = new ArrayList<>();
      for (Future<CandidateDraft> future : pool.invokeAll(tasks, 90, TimeUnit.SECONDS)) {
        try {
          results.add(future.get());
        } catch (Exception ex) {
          results.add(null); // A single probe failure/timeout must not drop the batch.
        }
      }
      return results;
    } catch (InterruptedException ex) {
      Thread.currentThread().interrupt();
      return List.of();
    } finally {
      pool.shutdownNow();
    }
  }

  /**
   * Load uniqueKey -> {format, scale, fields} for candidates whose link was already
   * measured in a previous run (scale carries a byte count), so we can skip re-probing.
   */
  private Map<String, String[]> loadResolvedProbes() {
    Map<String, String[]> map = new HashMap<>();
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(
             "SELECT UNIQUE_KEY, DATA_FORMAT, DATA_SCALE, DETECTED_FIELDS FROM DISCOVERY_CANDIDATES");
         ResultSet rs = statement.executeQuery()) {
      while (rs.next()) {
        String scale = rs.getString("DATA_SCALE");
        if (scale != null && scale.contains("bytes")) {
          map.put(rs.getString("UNIQUE_KEY"),
              new String[] {rs.getString("DATA_FORMAT"), scale, rs.getString("DETECTED_FIELDS")});
        }
      }
    } catch (SQLException ignored) {
      // Skip-cache is a pure optimization; on error we just probe everything.
    }
    return map;
  }

  private CandidateDraft draftFromDataCite(JsonNode item, Map<String, String[]> resolved) {
    JsonNode attributes = item.path("attributes");
    String doi = text(attributes, "doi");
    String title = firstTitle(attributes.path("titles"));
    String url = text(attributes, "url");
    if (title.isBlank() || (doi.isBlank() && url.isBlank())) {
      return null;
    }
    String publisher = text(attributes, "publisher");
    String repository = inferRepository(publisher, url);
    String description = firstDescription(attributes.path("descriptions"));
    String license = firstRights(attributes.path("rightsList"));
    String dataUrl = chooseDataUrl(attributes, url, doi);
    String paperUrl = doi.isBlank() ? url : "https://doi.org/" + doi;
    String uniqueKey = normalizeKey(!doi.isBlank() ? doi : dataUrl);

    // DataCite often ships native metadata we can use before any HTTP probing.
    String nativeFormats = joinArray(attributes.path("formats"));
    String nativeSize = firstArrayValue(attributes.path("sizes"));
    String subjects = joinSubjects(attributes.path("subjects"));

    String combined = (title + " " + description + " " + dataUrl + " " + publisher + " "
        + subjects + " " + nativeFormats).toLowerCase(Locale.ROOT);

    String format;
    String scale;
    String fields;
    String[] cached = resolved == null ? null : resolved.get(uniqueKey);
    if (cached != null) {
      // Already probed in an earlier run — reuse the stored result, skip the HTTP HEAD.
      format = cached[0];
      scale = cached[1];
      fields = (cached[2] == null || cached[2].isBlank()) ? detectFields(combined) : cached[2];
    } else {
      PreflightProbe rawProbe = probeDataUrl(dataUrl, combined);
      format = "待识别".equals(rawProbe.format()) && !nativeFormats.isBlank()
          ? detectFormat("", nativeFormats)
          : rawProbe.format();
      boolean scaleUnknown = "待下载清点".equals(rawProbe.scale()) || "链接预检失败".equals(rawProbe.scale());
      scale = scaleUnknown && !nativeSize.isBlank() ? nativeSize : rawProbe.scale();
      fields = rawProbe.fields();
    }
    PreflightProbe probe = new PreflightProbe(format, scale, fields, parserPlan(format, combined));

    String method = inferMethod(combined);
    int relevance = relevanceOf(combined, probe.format(), probe.fields(), method);
    int score = scoreCandidate(doi, dataUrl, license, probe, relevance);
    String recommendation = recommendation(title, doi, dataUrl, license, probe, relevance, score);
    return new CandidateDraft(
        "DataCite",
        title,
        doi,
        paperUrl,
        dataUrl,
        repository,
        license.isBlank() ? "待确认" : license,
        probe.format(),
        probe.scale(),
        method,
        probe.fields(),
        probe.parserPlan(),
        score,
        relevance,
        recommendation,
        uniqueKey
    );
  }

  private PreflightProbe probeDataUrl(String dataUrl, String combinedText) {
    String format = detectFormat(dataUrl, "");
    String scale = "待下载清点";
    String fields = detectFields(combinedText);
    String parserPlan = parserPlan(format, combinedText);
    if (dataUrl.isBlank() || !dataUrl.startsWith("http")) {
      return new PreflightProbe(format, scale, fields, parserPlan);
    }
    if (!OutboundUrlGuard.isSafe(dataUrl)) {
      // SSRF guard: never dereference a discovered URL that resolves to an internal host.
      return new PreflightProbe(format, "链接预检失败（安全拦截）", fields, parserPlan);
    }
    try {
      HttpRequest head = HttpRequest.newBuilder(URI.create(dataUrl))
          .method("HEAD", HttpRequest.BodyPublishers.noBody())
          .timeout(Duration.ofSeconds(8))
          .header("User-Agent", userAgent())
          .build();
      HttpResponse<Void> headResponse = httpClient.send(head, HttpResponse.BodyHandlers.discarding());
      String contentType = headResponse.headers().firstValue("content-type").orElse("");
      String contentLength = headResponse.headers().firstValue("content-length").orElse("");
      if (!contentLength.isBlank()) {
        scale = contentLength + " bytes";
      }
      format = detectFormat(dataUrl, contentType);
      if ("待识别".equals(format) && headResponse.statusCode() >= 200 && headResponse.statusCode() < 400) {
        HttpRequest sample = HttpRequest.newBuilder(URI.create(dataUrl))
            .GET()
            .timeout(Duration.ofSeconds(10))
            .header("Range", "bytes=0-" + (SAMPLE_BYTES - 1))
            .header("User-Agent", userAgent())
            .build();
        HttpResponse<byte[]> sampleResponse = httpClient.send(sample, HttpResponse.BodyHandlers.ofByteArray());
        if (sampleResponse.statusCode() >= 200 && sampleResponse.statusCode() < 400) {
          String sampleText = new String(sampleResponse.body(), 0, Math.min(sampleResponse.body().length, 4096), StandardCharsets.UTF_8);
          format = detectFormat(dataUrl, contentType + " " + sampleText);
          fields = detectFields(combinedText + " " + sampleText);
        }
      }
      return new PreflightProbe(format, scale, fields, parserPlan(format, combinedText));
    } catch (Exception ex) {
      return new PreflightProbe(format, "链接预检失败", fields, parserPlan);
    }
  }

  private UpsertResult upsertCandidate(CandidateDraft draft, ValidationReport report) throws SQLException {
    String now = Instant.now().toString();
    String vStatus = report == null ? "" : report.status();
    String vJson = serializeReport(report);
    String vAt = report == null ? "" : report.validatedAt();
    try (Connection connection = openConnection();
         PreparedStatement query = connection.prepareStatement(
             "SELECT ID, STATUS FROM DISCOVERY_CANDIDATES WHERE UNIQUE_KEY = ?")) {
      query.setString(1, draft.uniqueKey());
      try (ResultSet rs = query.executeQuery()) {
        if (rs.next()) {
          long id = rs.getLong("ID");
          try (PreparedStatement update = connection.prepareStatement("""
              UPDATE DISCOVERY_CANDIDATES
              SET SOURCE = ?, TITLE = ?, DOI = ?, PAPER_URL = ?, DATA_URL = ?, REPOSITORY = ?,
                  LICENSE_TEXT = ?, DATA_FORMAT = ?, DATA_SCALE = ?, METHOD_TEXT = ?,
                  DETECTED_FIELDS = ?, PARSER_PLAN = ?, SCORE = ?, RECOMMENDATION = ?, RELEVANCE = ?,
                  VALIDATION_STATUS = ?, VALIDATION_JSON = ?, VALIDATED_AT = ?, UPDATED_AT = ?
              WHERE ID = ?
              """)) {
            bindDraft(update, draft);
            update.setString(16, vStatus);
            update.setString(17, vJson);
            update.setString(18, vAt);
            update.setString(19, now);
            update.setLong(20, id);
            update.executeUpdate();
          }
          return new UpsertResult(false, true);
        }
      }
      try (PreparedStatement insert = connection.prepareStatement("""
          INSERT INTO DISCOVERY_CANDIDATES (
            SOURCE, TITLE, DOI, PAPER_URL, DATA_URL, REPOSITORY, LICENSE_TEXT,
            DATA_FORMAT, DATA_SCALE, METHOD_TEXT, DETECTED_FIELDS, PARSER_PLAN,
            SCORE, RECOMMENDATION, RELEVANCE, STATUS, REVIEW_NOTE, DISCOVERED_AT, UPDATED_AT, UNIQUE_KEY,
            VALIDATION_STATUS, VALIDATION_JSON, VALIDATED_AT
          ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'CANDIDATE', '', ?, ?, ?, ?, ?, ?)
          """)) {
        bindDraft(insert, draft);
        insert.setString(16, now);
        insert.setString(17, now);
        insert.setString(18, draft.uniqueKey());
        insert.setString(19, vStatus);
        insert.setString(20, vJson);
        insert.setString(21, vAt);
        insert.executeUpdate();
      }
      return new UpsertResult(true, false);
    }
  }

  private String serializeReport(ValidationReport report) {
    if (report == null) {
      return "";
    }
    try {
      return limit(objectMapper.writeValueAsString(report), 4000);
    } catch (Exception ex) {
      return "";
    }
  }

  private DiscoveryCandidateResponse toCandidate(CandidateDraft d) {
    return new DiscoveryCandidateResponse(
        0L, d.source(), d.title(), d.doi(), d.paperUrl(), d.dataUrl(), d.repository(),
        d.license(), d.dataFormat(), d.dataScale(), d.method(), d.detectedFields(),
        d.parserPlan(), d.score(), d.relevance(), d.recommendation(), "CANDIDATE", "",
        "", "", "", "", List.of());
  }

  private void bindDraft(PreparedStatement statement, CandidateDraft draft) throws SQLException {
    statement.setString(1, limit(draft.source(), 80));
    statement.setString(2, limit(draft.title(), 500));
    statement.setString(3, limit(draft.doi(), 180));
    statement.setString(4, limit(draft.paperUrl(), 500));
    statement.setString(5, limit(draft.dataUrl(), 500));
    statement.setString(6, limit(draft.repository(), 120));
    statement.setString(7, limit(draft.license(), 180));
    statement.setString(8, limit(draft.dataFormat(), 80));
    statement.setString(9, limit(draft.dataScale(), 120));
    statement.setString(10, limit(draft.method(), 180));
    statement.setString(11, limit(draft.detectedFields(), 800));
    statement.setString(12, limit(draft.parserPlan(), 500));
    statement.setInt(13, draft.score());
    statement.setString(14, limit(draft.recommendation(), 1000));
    statement.setInt(15, draft.relevance());
  }

  private void saveRun(DiscoveryRunResponse run, String operator) {
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement("""
             MERGE INTO DISCOVERY_RUNS
               (RUN_ID, STARTED_AT, FINISHED_AT, STATUS, DISCOVERED, INSERTED, UPDATED,
                AUTO_PROMOTED, AUTO_ARCHIVED, MESSAGE, SOURCE_STATS)
             KEY (RUN_ID)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
             """)) {
      statement.setString(1, run.runId());
      statement.setString(2, run.startedAt());
      statement.setString(3, run.finishedAt());
      statement.setString(4, run.status());
      statement.setInt(5, run.discovered());
      statement.setInt(6, run.inserted());
      statement.setInt(7, run.updated());
      statement.setInt(8, run.autoPromoted());
      statement.setInt(9, run.autoArchived());
      statement.setString(10, limit(run.message() + " 操作人: " + operator, 1000));
      statement.setString(11, limit(serializeSourceStats(run.sourceStats()), 4000));
      statement.executeUpdate();
    } catch (SQLException ignored) {
      // Discovery run history is best effort.
    }
  }

  private String serializeSourceStats(List<DiscoverySourceStat> stats) {
    if (stats == null || stats.isEmpty()) {
      return "";
    }
    try {
      return objectMapper.writeValueAsString(stats);
    } catch (Exception ex) {
      return "";
    }
  }

  private DiscoveryCandidateResponse findCandidate(long id) {
    try (Connection connection = openConnection();
         PreparedStatement statement = connection.prepareStatement(
             "SELECT * FROM DISCOVERY_CANDIDATES WHERE ID = ?")) {
      statement.setLong(1, id);
      try (ResultSet rs = statement.executeQuery()) {
        if (!rs.next()) {
          throw new ApiException(HttpStatus.NOT_FOUND, "找不到自动发现候选: " + id);
        }
        return candidateFrom(rs);
      }
    } catch (SQLException ex) {
      throw databaseError(ex);
    }
  }

  private DiscoveryCandidateResponse candidateFrom(ResultSet rs) throws SQLException {
    return new DiscoveryCandidateResponse(
        rs.getLong("ID"),
        rs.getString("SOURCE"),
        rs.getString("TITLE"),
        rs.getString("DOI"),
        rs.getString("PAPER_URL"),
        rs.getString("DATA_URL"),
        rs.getString("REPOSITORY"),
        rs.getString("LICENSE_TEXT"),
        rs.getString("DATA_FORMAT"),
        rs.getString("DATA_SCALE"),
        rs.getString("METHOD_TEXT"),
        rs.getString("DETECTED_FIELDS"),
        rs.getString("PARSER_PLAN"),
        rs.getInt("SCORE"),
        rs.getInt("RELEVANCE"),
        rs.getString("RECOMMENDATION"),
        rs.getString("STATUS"),
        rs.getString("REVIEW_NOTE"),
        rs.getString("DISCOVERED_AT"),
        rs.getString("UPDATED_AT"),
        rs.getString("VALIDATION_STATUS"),
        rs.getString("VALIDATED_AT"),
        parseValidationChecks(rs.getString("VALIDATION_JSON"))
    );
  }

  private List<ValidationCheck> parseValidationChecks(String json) {
    if (json == null || json.isBlank()) {
      return List.of();
    }
    try {
      ValidationReport report = objectMapper.readValue(json, ValidationReport.class);
      return report.checks() == null ? List.of() : report.checks();
    } catch (Exception ex) {
      return List.of();
    }
  }

  private DiscoveryRunResponse runFrom(ResultSet rs) throws SQLException {
    return new DiscoveryRunResponse(
        rs.getString("RUN_ID"),
        rs.getString("STARTED_AT"),
        rs.getString("FINISHED_AT"),
        rs.getString("STATUS"),
        rs.getInt("DISCOVERED"),
        rs.getInt("INSERTED"),
        rs.getInt("UPDATED"),
        rs.getInt("AUTO_PROMOTED"),
        rs.getInt("AUTO_ARCHIVED"),
        rs.getString("MESSAGE"),
        parseSourceStats(rs.getString("SOURCE_STATS"))
    );
  }

  private List<DiscoverySourceStat> parseSourceStats(String json) {
    if (json == null || json.isBlank()) {
      return List.of();
    }
    try {
      return List.of(objectMapper.readValue(json, DiscoverySourceStat[].class));
    } catch (Exception ex) {
      return List.of();
    }
  }

  private static DiscoverySourceResponse source(String key, String name, String url, String status, String cadence, String capability) {
    return new DiscoverySourceResponse(key, name, url, status, cadence, capability);
  }

  private static String firstTitle(JsonNode titles) {
    if (titles.isArray() && !titles.isEmpty()) {
      return text(titles.get(0), "title");
    }
    return "";
  }

  private static String firstDescription(JsonNode descriptions) {
    if (descriptions.isArray() && !descriptions.isEmpty()) {
      return text(descriptions.get(0), "description");
    }
    return "";
  }

  private static String firstRights(JsonNode rights) {
    if (rights.isArray() && !rights.isEmpty()) {
      String title = text(rights.get(0), "rights");
      String uri = text(rights.get(0), "rightsUri");
      return title.isBlank() ? uri : title;
    }
    return "";
  }

  private static String joinArray(JsonNode array) {
    if (!array.isArray() || array.isEmpty()) {
      return "";
    }
    List<String> values = new ArrayList<>();
    for (JsonNode node : array) {
      String value = node.asText("").trim();
      if (!value.isBlank()) {
        values.add(value);
      }
    }
    return String.join(" ", values);
  }

  private static String firstArrayValue(JsonNode array) {
    if (array.isArray() && !array.isEmpty()) {
      return array.get(0).asText("").trim();
    }
    return "";
  }

  private static String joinSubjects(JsonNode subjects) {
    if (!subjects.isArray() || subjects.isEmpty()) {
      return "";
    }
    List<String> values = new ArrayList<>();
    for (JsonNode node : subjects) {
      String value = node.path("subject").asText("").trim();
      if (!value.isBlank()) {
        values.add(value);
      }
    }
    return String.join(" ", values);
  }

  private static String stripHtml(String value) {
    if (value == null || value.isBlank()) {
      return "";
    }
    return value.replaceAll("<[^>]+>", " ").replaceAll("\\s+", " ").trim();
  }

  private static String zenodoLicense(JsonNode license) {
    if (license == null || license.isMissingNode()) {
      return "";
    }
    if (license.isTextual()) {
      return license.asText("").trim();
    }
    return license.path("id").asText("").trim();
  }

  private static String firstNonBlank(String... values) {
    for (String value : values) {
      if (value != null && !value.isBlank()) {
        return value.trim();
      }
    }
    return "";
  }

  private static String chooseDataUrl(JsonNode attributes, String url, String doi) {
    JsonNode contentUrl = attributes.path("contentUrl");
    if (contentUrl.isArray() && !contentUrl.isEmpty()) {
      return contentUrl.get(0).asText("");
    }
    if (contentUrl.isTextual() && !contentUrl.asText("").isBlank()) {
      return contentUrl.asText("");
    }
    return url.isBlank() && !doi.isBlank() ? "https://doi.org/" + doi : url;
  }

  private static String text(JsonNode node, String field) {
    return node == null ? "" : node.path(field).asText("").trim();
  }

  private static String inferRepository(String publisher, String url) {
    String combined = (publisher + " " + url).toLowerCase(Locale.ROOT);
    if (combined.contains("zenodo")) return "Zenodo";
    if (combined.contains("figshare")) return "Figshare";
    if (combined.contains("materials cloud") || combined.contains("materialscloud")) return "Materials Cloud";
    if (combined.contains("nomad")) return "NOMAD";
    if (combined.contains("materials project")) return "Materials Project";
    if (combined.contains("aflow")) return "AFLOW";
    if (combined.contains("oqmd")) return "OQMD";
    return publisher.isBlank() ? "DataCite indexed repository" : publisher;
  }

  private static String detectFormat(String url, String hint) {
    String text = (url + " " + hint).toLowerCase(Locale.ROOT);
    if (text.contains(".cif") || text.contains("_cell_length") || text.contains("chemical_formula")) return "CIF";
    if (text.contains("poscar") || text.contains("contcar")) return "POSCAR/CONTCAR";
    if (text.contains(".extxyz")) return "EXTXYZ";
    if (text.contains(".xyz")) return "XYZ";
    if (text.contains(".h5") || text.contains(".hdf5") || text.contains("hdf5")) return "HDF5";
    if (text.contains("lmdb")) return "LMDB";
    if (text.contains(".json") || text.contains("application/json")) return "JSON";
    if (text.contains(".csv") || text.contains("text/csv")) return "CSV";
    if (text.contains(".zip") || text.contains(".tar") || text.contains(".tgz") || text.contains(".gz")) return "压缩包";
    return "待识别";
  }

  private static String detectFields(String text) {
    Set<String> fields = new LinkedHashSet<>();
    if (containsAny(text, "structure", "crystal", "cif", "poscar", "xyz", "coordinates")) fields.add("structure/coordinates");
    if (containsAny(text, "energy", "formation energy", "total energy")) fields.add("energy");
    if (containsAny(text, "force", "forces")) fields.add("force");
    if (containsAny(text, "stress", "virial")) fields.add("stress");
    if (containsAny(text, "band gap", "bandgap", "homo", "lumo")) fields.add("bandgap/electronic");
    if (containsAny(text, "phonon", "frequency")) fields.add("phonon");
    if (containsAny(text, "dielectric", "permittivity")) fields.add("dielectric");
    if (containsAny(text, "elastic", "bulk modulus", "shear modulus")) fields.add("elastic");
    if (fields.isEmpty()) fields.add("metadata only");
    return String.join(", ", fields);
  }

  private static String parserPlan(String format, String text) {
    return switch (format) {
      case "CIF" -> "通用结构解析：pymatgen Structure.from_file 或 ASE read；需检查晶胞、元素、周期性。";
      case "POSCAR/CONTCAR" -> "VASP 结构解析：ASE/pymatgen 读取 POSCAR/CONTCAR；需补 INCAR/KPOINTS/POTCAR 元数据。";
      case "XYZ", "EXTXYZ" -> "分子/构型解析：ASE read；EXTXYZ 可同时提取 energy/forces/stress。";
      case "HDF5" -> "HDF5 专用适配器：先列 root/group/dataset，再映射 energy/force/coordinates。";
      case "LMDB" -> "ASE-LMDB 适配器：逐条抽样反序列化 Atoms/metadata。";
      case "JSON", "CSV" -> "表格/结构化适配器：抽样识别字段，必要时用 pymatgen/ASE 解析结构字符串。";
      case "压缩包" -> "下载清单后解压抽样，按内部文件类型分派 CIF/POSCAR/XYZ/HDF5 解析器。";
      default -> text.contains("structure") ? "先抽样下载识别格式，再调用 ASE/pymatgen 解析结构。" : "先人工确认下载入口和文件格式。";
    };
  }

  private static String inferMethod(String text) {
    Set<String> methods = new LinkedHashSet<>();
    if (text.contains("vasp")) methods.add("VASP");
    if (text.contains("dft") || text.contains("density functional")) methods.add("DFT");
    if (text.contains("pbe")) methods.add("PBE");
    if (text.contains("hse")) methods.add("HSE");
    if (text.contains("scan")) methods.add("SCAN");
    if (text.contains("b3lyp")) methods.add("B3LYP");
    if (text.contains("wb97") || text.contains("ωb97")) methods.add("wB97X/wB97M");
    if (methods.isEmpty()) methods.add("待从论文/元数据确认");
    return String.join(" / ", methods);
  }

  /**
   * Materials-relevance (0-100): how on-topic a candidate is for computational
   * materials science, kept separate from readiness so a complete-but-off-topic
   * record (e.g. a biology dataset that merely mentions "structure") cannot drift
   * above the auto-promote threshold on completeness alone.
   */
  private static int relevanceOf(String text, String format, String fields, String method) {
    boolean domain = containsAny(text,
        "material", "crystal", "molecul", "polymer", "alloy", "catal", "perovskite",
        "semiconductor", "mof", "zeolite", "2d material", "battery", "electrolyte",
        "photovolt", "oxide", "nanomaterial", "solid-state", "solid state", "lattice");
    boolean methodSig = !"待从论文/元数据确认".equals(method);
    boolean property = !"metadata only".equals(fields);
    boolean formatSig = !"待识别".equals(format);
    boolean dataSig = containsAny(text,
        "dataset", "data set", "trajector", "configuration", "structures", "energies",
        "first-principles", "first principles", "ab initio", "ab-initio",
        "high-throughput", "high throughput", "potential energy surface");
    int categories = (domain ? 1 : 0) + (methodSig ? 1 : 0) + (property ? 1 : 0)
        + (formatSig ? 1 : 0) + (dataSig ? 1 : 0);
    int relevance = Math.min(100, categories * 22);
    boolean offTopic = containsAny(text,
        "clinical", "patient", "genome", "genomic", "transcriptom", "questionnaire",
        "survey response", "socioeconomic", "gravitational wave", "seismic",
        "earthquake", "galaxy", "exoplanet", "biodiversity", "species occurrence");
    if (offTopic && !domain) {
      relevance = Math.max(0, relevance - 55);
    }
    return relevance;
  }

  private static int scoreCandidate(String doi, String dataUrl, String license, PreflightProbe probe, int relevance) {
    int score = (int) Math.round(relevance * 0.30); // up to 30 from materials relevance
    if (!doi.isBlank()) score += 16;
    if (!dataUrl.isBlank()) score += 16;
    if (hasUsableLicense(license)) score += 12;
    if (!"待识别".equals(probe.format())) score += 14;
    if (!"metadata only".equals(probe.fields())) score += 12;
    return Math.min(score, 100);
  }

  private static String recommendation(String title, String doi, String dataUrl, String license, PreflightProbe probe, int relevance, int score) {
    List<String> parts = new ArrayList<>();
    parts.add("自动发现候选：" + title);
    parts.add("评分 " + score + "（相关度 " + relevance + "），格式 " + probe.format() + "，字段 " + probe.fields() + "。");
    if (doi.isBlank()) parts.add("缺 DOI，需要人工核验来源。");
    if (dataUrl.isBlank()) parts.add("缺数据下载入口，需要人工补链接。");
    if (!hasUsableLicense(license)) parts.add("许可证未识别，不能直接公开下载。");
    if (relevance < RELEVANCE_NOISE_FLOOR) {
      parts.add("材料相关度偏低，疑似跨领域噪声，已自动排除转入。");
    }
    if (score >= 80) {
      parts.add("建议优先审核，并进入解析适配器开发。");
    } else if (score >= 60) {
      parts.add("建议保留候选，先补链接/许可证/格式说明。");
    } else {
      parts.add("建议暂缓接入，仅作为线索。");
    }
    return String.join(" ", parts);
  }

  private static String inferDataType(DiscoveryCandidateResponse candidate) {
    String text = (candidate.title() + " " + candidate.detectedFields()).toLowerCase(Locale.ROOT);
    if (text.contains("polymer")) return "聚合物";
    if (text.contains("mof")) return "MOF";
    if (text.contains("reaction")) return "反应路径";
    if (text.contains("molecule") || text.contains("xyz")) return "小分子构象";
    if (text.contains("2d")) return "二维材料";
    return "晶体材料";
  }

  private static boolean containsAny(String text, String... tokens) {
    for (String token : tokens) {
      if (text.contains(token)) {
        return true;
      }
    }
    return false;
  }

  private static String normalizeDecision(String value) {
    String decision = value == null ? "" : value.trim().toUpperCase(Locale.ROOT);
    if (decision.isBlank()) {
      return "REVIEW";
    }
    if (!List.of("CANDIDATE", "REVIEW", "APPROVED", "REJECTED", "ARCHIVED").contains(decision)) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "候选状态仅支持 CANDIDATE、REVIEW、APPROVED、REJECTED、ARCHIVED");
    }
    return decision;
  }

  private static String optional(String value, int maxLength) {
    String text = value == null ? "" : value.trim();
    if (text.length() > maxLength) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "输入内容过长");
    }
    return text;
  }

  private static String limit(String value, int maxLength) {
    String text = value == null ? "" : value.trim();
    return text.length() <= maxLength ? text : text.substring(0, maxLength);
  }

  /**
   * Canonicalize a dedup key so the same dataset reached via different surfaces
   * (raw DOI, doi.org URL, trailing slash) collapses to one candidate.
   */
  private static String normalizeKey(String value) {
    if (value == null) {
      return "";
    }
    String v = value.trim().toLowerCase(Locale.ROOT);
    if (v.startsWith("https://doi.org/")) {
      v = v.substring("https://doi.org/".length());
    } else if (v.startsWith("http://doi.org/")) {
      v = v.substring("http://doi.org/".length());
    } else if (v.startsWith("doi:")) {
      v = v.substring("doi:".length());
    }
    while (v.endsWith("/")) {
      v = v.substring(0, v.length() - 1);
    }
    return v;
  }

  private Connection openConnection() throws SQLException {
    return DriverManager.getConnection(resolveJdbcUrl(), "sa", "");
  }

  private String resolveJdbcUrl() {
    String cached = jdbcUrl;
    if (cached != null) {
      return cached;
    }
    synchronized (this) {
      if (jdbcUrl == null) {
        Path path = Paths.get(properties.getDbPath());
        Path cwd = Paths.get("").toAbsolutePath();
        Path candidate = path.isAbsolute() ? path : cwd.resolve(path).normalize();
        Path projectCandidate = path.isAbsolute() ? path : cwd.resolve("..").resolve(path).normalize();
        if (!path.isAbsolute() && Files.isDirectory(projectCandidate.getParent())) {
          candidate = projectCandidate;
        }
        try {
          Files.createDirectories(candidate.toAbsolutePath().getParent());
        } catch (Exception ex) {
          throw new IllegalStateException("创建自动发现数据库目录失败: " + ex.getMessage(), ex);
        }
        jdbcUrl = "jdbc:h2:" + candidate.toAbsolutePath().normalize().toString().replace('\\', '/');
      }
      return jdbcUrl;
    }
  }

  private static ApiException databaseError(SQLException ex) {
    return new ApiException(HttpStatus.INTERNAL_SERVER_ERROR, "读取自动发现数据库失败: " + ex.getMessage());
  }

  private record CandidateDraft(
      String source,
      String title,
      String doi,
      String paperUrl,
      String dataUrl,
      String repository,
      String license,
      String dataFormat,
      String dataScale,
      String method,
      String detectedFields,
      String parserPlan,
      int score,
      int relevance,
      String recommendation,
      String uniqueKey
  ) {
  }

  private record PreflightProbe(String format, String scale, String fields, String parserPlan) {
  }

  private record UpsertResult(boolean inserted, boolean updated) {
  }

  private record TriageResult(int promoted, int archived) {
  }

  private record DiscoverAllResult(List<CandidateDraft> drafts, List<DiscoverySourceStat> stats) {
  }

  private record SourceResult(DiscoverySourceStat stat, List<CandidateDraft> drafts) {
  }

  /** A single source connector: produces drafts and may throw on network/parse failure. */
  @FunctionalInterface
  private interface DraftSupplier {
    List<CandidateDraft> get() throws Exception;
  }
}
